#!/bin/bash

if [[ $(systemctl is-active jupyterhub) == "active" ]]; then
    echo 🐍
    show() {
        $HOME/.scripts/non-transparent-terminal -n jupyterhub -f mono:pixelsize=18 -e $HOME/.config/i3blocks/jupyterhub/jupyterhubstatus;
    }
    case $BLOCK_BUTTON in
        1) show ;;
    esac
else
  echo ""
fi

