#!/bin/bash

if [ -f /etc/systemd/system/jupyterhub.service ]; then
    if [[ $(systemctl is-active jupyterhub) == "active" ]]; then
        echo 🪐
        show() {
            notify-send "Jupyterhub" "active\n(right click to stop)\n\n$($HOME/.config/i3blocks/jupyterhub/jupyterhubstatus)"
        }
        stopp() {
            $HOME/.config/i3/non-transparent-terminal -n tjupyterhub -f mono:pixelsize=18 -e $HOME/.config/i3blocks/jupyterhub/stop;
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) stopp ;;
            #3) pkill -f tjupyterhub
        esac
    else
        echo "❌"
        show() {
            notify-send "Jupyterhub" "inactive\n(right click to start)\n\n$($HOME/.config/i3blocks/jupyterhub/jupyterhubstatus)"
        }
        startt() {
            $HOME/.config/i3/non-transparent-terminal -n tjupyterhub -f mono:pixelsize=18 -e $HOME/.config/i3blocks/jupyterhub/start;
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) startt ;;
        esac
    fi
fi

