#!/bin/bash

if [[ $(systemctl is-active jupyterhub) == "active" ]]; then
    echo 🪐 
    show() {
        #$HOME/.scripts/non-transparent-terminal -n tjupyterhub -f mono:pixelsize=18 -e $HOME/.config/i3blocks/jupyterhub/jupyterhubstatus;
        notify-send "Jupyterhub" "active\n(right click to stop)\n\n$($HOME/.config/i3blocks/jupyterhub/jupyterhubstatus)"
    }
    stopp() {
        $HOME/.scripts/non-transparent-terminal -n tjupyterhub -f mono:pixelsize=18 -e sudo systemctl stop jupyterhub;
    }
    case $BLOCK_BUTTON in
        1) show ;;
        3) stopp ;;
        #3) pkill -f tjupyterhub
    esac
else
    echo "❌"
    show() {
        #$HOME/.scripts/non-transparent-terminal -n tjupyterhub -f mono:pixelsize=18 -e $HOME/.config/i3blocks/jupyterhub/jupyterhubstatus;
        notify-send "Jupyterhub" "inactive\n(right click to start)\n\n$($HOME/.config/i3blocks/jupyterhub/jupyterhubstatus)"
    }
    startt() {
        $HOME/.scripts/non-transparent-terminal -n tjupyterhub -f mono:pixelsize=18 -e sudo systemctl start jupyterhub;
    }
    case $BLOCK_BUTTON in
        1) show ;;
        3) startt ;;
    esac
fi

