#!/usr/bin/python3

import os
import sys
from subprocess import call, check_output, CalledProcessError, Popen, PIPE

try:
    with open(os.path.expanduser("~/.config/i3/config"), "r") as file:
        content = file.read().split("\n")

    content = [(comment.strip(), command.strip()) for comment, command in zip(content, content[1:]) if command.startswith("bindsym")]

    normal = []
    shift = []
    other = []
    commands = {}
    comments = {}
    for comment, line in content:
        line = line.replace("bindsym","").replace("--no-startup-id","").replace("\t"," ").replace("$mod","◻️").replace("Shift","⬆️").strip()
        while "  " in line:
            line = line.replace("  ", " ")
        line = line.split(" ")
        shortcut = line[0]
        command = line[1:]
        if not "◻️" in shortcut:
            other.append(shortcut)
        elif not "⬆️" in shortcut:
            normal.append(shortcut)
        else:
            shortcut = "◻️+"+shortcut[6:] + "⬆️"
            shift.append(shortcut)

        comments[shortcut] = comment.replace("#","").strip() if comment.startswith("#") else " ".join(command)
        commands[comments[shortcut]] = command

    shortcuts = sorted(normal+shift, key=str.lower) + sorted(other, key=str.lower)

    def maybe_shift_shortcut(shortcut):
        if shortcut.endswith("⬆️"):
            return shortcut.replace("⬆️","").replace("◻️+", "◻️+⬆️+")
        return shortcut
    content = [maybe_shift_shortcut(shortcut) + ": " + comments[shortcut] for shortcut in shortcuts]

    dmenu_commands = Popen(["echo", "-n", "\n".join(content)], stdout=PIPE).stdout
    comment = check_output(["dmenu"] + sys.argv[1:], stdin = dmenu_commands).decode().split(":")[1].strip()
    command = commands[comment]
    # call the final layout command
    _command = " ".join(command)
    if not "$" in _command:
        call(["i3-msg"] + command)
        print(command)
    else:
        call(["notify-send", "Cannot execute command", f"not able to evaluate '{_command}'"])
except Exception as e:
    call(["notify-send", str(e)])

