#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____ 
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \  
#   | |   | |_/\| |-|||  __/| \_/||    /  | |  
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/  
#


# Toggle floating dropdown_terminal terminal in i3, or start if non-existing.

if xwininfo -tree -root | grep dropdown_terminal;
then
	echo "Window detected."
    i3 [instance="dropdown_terminal"] scratchpad show;
else
	echo "Window not detected... spawning."
    ($TERMINAL -n dropdown_terminal -f mono:pixelsize=18 -e tmux new-session -A -s dropdown_terminal) & disown;
    sleep 0.15;
    i3 [instance="dropdown_terminal"] scratchpad show;
fi
