#!/usr/bin/env bash

# DEFAULT="http://getwallpapers.com/wallpaper/full/f/8/1/74346.jpg"
DEFAULT="https://www.pixelstalk.net/wp-content/uploads/2016/06/HD-Minimal-Wallpapers.png"

if [ $1 ]; then
    WALL=$1
else
    WALL=$DEFAULT
fi

# try to copy file
cp "$WALL" /tmp/wall

# if copying fails, it's probably a URL, download it with curl.
if [ $? -ne 0 ]; then
    curl "$WALL" -o /tmp/wall
fi

# convert downloaded file to ~/.config/wallpaper.png
convert -quality 100 -resize 1920x1080 $2 /tmp/wall ~/.config/wallpaper.png

# and convert the inverse of the file to ~/.config/lockscreen.png
convert -quality 100  -negate ~/.config/wallpaper.png ~/.config/lockscreen.png

# give some time to finish conversions
sleep 2

# update the background with feh
feh --bg-scale ~/.config/wallpaper.png
