#!/usr/bin/env bash

# custom script that replaces split toggle command of i3

orientation=$(cat ~/.orientation) || "horizontal"

echo $orientation

if [ $orientation == "horizontal" ]; then
    opposite_orientation="vertical"
else
    opposite_orientation="horizontal"
fi

echo $opposite_orientation

i3 split $opposite_orientation && notify-send "split" $opposite_orientation && echo $opposite_orientation > ~/.orientation
