#!/usr/bin/env bash
# alias ls='ls -hN --color=auto --group-directories-first'
# alias ls='ls -hN --color=auto --group-directories-first'

LS=$(which lsd 2> /dev/null)
[ $? -ne 0 ] && LS=/usr/bin/ls
$LS $@
