#!/usr/bin/env bash

# run a file in a tmux session named after the command to run it


COMMAND="diff"
FILENAME=$1


tmux kill-session -t git
tmux new-session -s git -d;

echo "git diff..."
tmux send-keys -t git cd Space $PWD Enter nvim Space $FILENAME Enter :G$COMMAND Enter 

tmux attach-session -t git

