#!/usr/bin/env bash

# run a file in a tmux session named after the command to run it


COMMAND=$1
FILENAME=$2


tmux kill-session -t git
tmux new-session -s git -d;

echo "git_status..."
tmux send-keys -t git cd Space $PWD Enter nvim Space $FILENAME Enter :G$COMMAND Enter C-k :bd Enter


tmux attach-session -t git

