#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

# Widget selection
#--------------------------------------------------------------------------------

# the widget delimiter ascii code (ascii code should match with code defined in dwm config.h):
DELIM_ASCII_CODE=32 # 32: ascii code for space

# the delimiter is derived form the ascii code:
DELIM=$(printf "\x$(printf %x $DELIM_ASCII_CODE)")

# folder where widgets and status bar will be cached:
CACHEDIR="$HOME/.cache/dwm_status"
mkdir -p "$CACHEDIR"

# The widget array determines which widgets are included in the status bar.
# Each included widget needs to be defined below by a function with the same name.

setstatus(){
    status \
    network \
    transmission \
    playercontrol \
    appointments \
    syncthing \
    sshd \
    sshtunnel \
    jellyfin \
    jupyterhub \
    openvpn \
    openconnect \
    cups \
    gpg \
    email \
    pacmanstatus \
    volume \
    brightness \
    battery \
    alpha \
    weather \
    calendar \
    clock \
    # services \
    # bluetooth \
    # memory \
    # cpu \
    # disk \
    # localip \
    # publicip \
    # wifi \
}


# Parse arguments
#--------------------------------------------------------------------------------

usage(){
    >&2 echo "usage: dwm_status [widget-name|widget-index] [mouse-button-index 1|2|3]"
    >&2 echo ""
    >&2 echo "* without arguments: status bar is updated."
    >&2 echo "* with arguments: when a widget name OR widget-index is specified, a mouse button index (1,2,3) MUST be specified as well."
    >&2 echo ""
    exit "$1"
}

[ "$1" = "-h" ] || [ "$1" = "--help" ] && usage 0
WIDGET="$1"
BUTTON="$2"
if  [ -n "$WIDGET" ]; then
    [ -z "$BUTTON" ] && usage 1
    [ "$BUTTON" -ge 1 ] 2> /dev/null || usage 1
    [ "$BUTTON" -le 3 ] 2> /dev/null || usage 1
fi


# Status Command
#--------------------------------------------------------------------------------

# the status function pastes the output of each widget (defined below) together
# into the status bar of dwm (by using xsetroot).

status(){
    idx=0
    rootname=""
    tempdelim="#DELIM#" # temporary delimiter, will be replaced by $DELIM later on. Defining a temporary delimiter is necessary as it ensures one can use a normal space as delimiter.
    if [ ! -z "$BUTTON" ]; then
       "$WIDGET$BUTTON" 2> /dev/null && return # if widget name given
    fi
    for widget in "$@" # if no widget or widget index given
    do
        out=$($widget)
        if [ -n "$out" ]; then
            if [ -n "$BUTTON" ] && [ "$WIDGET" -eq "$idx" ]; then
                "$widget$BUTTON" > /dev/null 2>/dev/null || usage 1
                out="$("$widget")"
            fi
            rootname="$rootname $out$tempdelim"
            idx=$((idx+1))
        fi
    done
    # unicode space U+2000:
    unicodespace=$(printf "$(printf '\\%o' $(printf %08x 0x2000 | sed 's/../0x& /g'))" | iconv -f UTF-32BE -t UTF-8)
    # replace all normal spaces by the unicode space (ascii space is reserved as a possible delimiter):
    rootname="$unicodespace$(echo "$rootname" | sed "s/[ ]/$unicodespace/g" | sed "s/$tempdelim/$DELIM/g" | sed "s/$DELIM\$//g" )$unicodespace"
    xsetroot -name "$rootname" > /dev/null 2>/dev/null
    echo "$rootname" > "$CACHEDIR/status" 2> /dev/null
}


# Helper functions
#--------------------------------------------------------------------------------

notifyservice(){
    name="$1"
    [ -z "$2" ] || icon="$2 "
    dte="$(date +'%a %Y-%m-%d')"
    tz="$(timedatectl | grep "Time zone" | sed 's/^[^(]*(\([^,]*\),.*/\1/g')"
    title="$(echo "$name" | sed 's/org.cups.cupsd/CUPS printer/g' | sed 's/^[ ]*//g' )"
    status="$(systemctl status "$name" | grep Active: | sed 's/^[^)]*)[ ]*//g' | sed "s/$dte //g" | sed "s/ $tz//g" | sed 's/;[ ]/\n/g' | sed 's/^[ ]*//g' )"
    suffix="\n[  +  + s: toggle any service ]"
    if systemctl is-active "$name" > /dev/null 2>/dev/null; then
        notify-send "$icon$title service 🔵" "\nactive $status\n\n[ middle click to stop ]$suffix"
    else
        notify-send "$icon$title service 🔴" "\ndead $status\n\n[ middle click to start ]$suffix"
    fi
}

toggleservice(){
    name=$1
    if systemctl is-active "$name" > /dev/null 2>/dev/null; then
        sudo -A -p "[sudo] password to stop $name.service" systemctl stop "$name"
    else
        sudo -A -p "[sudo] password to restart $name.service" systemctl start "$name"
    fi
}


# Widgets
#--------------------------------------------------------------------------------

# -----------

# shows window transparency (defined in Xresources, enabled by picom)
alpha(){ # window transparency
    if pidof picom > /dev/null; then
        echo " $("$HOME/.scripts/x/alpha" get)%"
    fi
}
alpha1(){ # mouse-button 1 action for alpha widget
    notify-send "[α] window transparency" "\n[  + a: decrease transparency ]\n[  +  + a: increase transparency ]"
}

# -----------

# shows battery percentage left
battery(){ # battery
    pct=$(cat /sys/class/power_supply/BAT*/capacity 2> /dev/null | head -1) || return
    [ -z "$pct" ] && return
    batstatus=$(cat /sys/class/power_supply/BAT*/status | head -1)
    if [ "$batstatus" = "Discharging" ] > /dev/null 2>/dev/null; then
        [ "$pct" -gt 90 ] && echo " $pct%" && return
        [ "$pct" -gt 60 ] && echo " $pct%" && return
        [ "$pct" -gt 30 ] && echo " $pct%" && return
        [ "$pct" -gt  5 ] && echo " $pct%" && return
        echo " $pct%" && return
    fi
    echo " $pct%"
}
battery1(){ # mouse-button 1 action for battery widget
    pct="$(cat /sys/class/power_supply/BAT*/capacity | head -1)"
    batstatus=$(cat /sys/class/power_supply/BAT*/status | head -1)
    timeleft="   $(acpi -b | sed 's/.*,//g' | sed 's/^[ ]*//g' | sed 's/^00://g')"
    if [ "$batstatus" = "Discharging" ] > /dev/null 2>/dev/null; then
        [ "$pct" -gt 95 ] && notify-send "🔋 battery fully charged." "$timeleft" && return
        notify-send "🔋 battery discharging." "$timeleft"
        return
    fi
    [ "$pct" -gt 95 ] && notify-send "🔌 battery fully charged." && return
    notify-send "🔌 battery charging." "$timeleft"
}

# -----------

# control brightness
brightness(){ # screen brightness
    light -L 2> /dev/null | grep backlight > /dev/null || return
    printf " %.0f%%" "$(light)" 2> /dev/null
}
brightness1(){ # mouse-button 1 action for brightness widget
    brightness=$(printf "%.0f%%" "$(light)")
    notify-send "☀ brightness [$brightness]" "\n[  + F11: brightness up   ]\n[  + F12: brightness down ]"
}

# -----------

# show  if bluetooth is connected,  otherwise
bluetooth(){ # bluetooth
    [ ! -d /sys/class/bluetooth ] && echo "" && return
    device=$(echo exit | bluetoothctl | grep -o -m 1 "\b\[.*\]" | sed "s/.*\[\(.*\)\].*/\1/g")
    [ "$device" = "bluetooth" ] && echo  || echo 
}
bluetooth1(){ # mouse-button 1 action for bluetooth widget
    device=$(echo exit | bluetoothctl | grep -o -m 1 "\b\[.*\]" | sed "s/.*\[\(.*\)\].*/\1/g")
    if [ "$device" = "bluetooth" ]; then
        notify-send " Bluetooth disconnected" "\n[ middle click /  + b to connect ]"
    else
        notify-send " Bluetooth connected" "to $device\n\n[ middle click /  + b to disconnect ]"
    fi
}
bluetooth2(){ # mouse-button 1 action for bluetooth widget
    dmenu_bluetooth
}

# -----------

# show time of current/next appointment.
appointments(){
    hm="$(grep "$(date +'%m/%d/%Y')" "$HOME/.calcurse/apts" | sed 's/!/|/g' | sed 's/[^@]*@\ \([0-9]*:[0-9]*\)[^@]*@[^|]*|/\1: /g' | grep "$(date +'%H')" | sed 's/^\([0-9][0-9]:[0-9][0-9]\).*/\1/g')"
    if [ -z "$hm" ]; then
        next=$(calcurse --next | sed '/next.*/d')
        [ -z "$next" ] && return
        H=$(date +'%H' | sed 's/^0//g')
        M=$(date +'%M' | sed 's/^0//g')
        h=$(echo "$next" | sed 's/^[^0-9]*\([0-9]*\).*/\1/g' | sed 's/^0//g')
        m=$(echo "$next" | sed 's/^[^:]*:[^0-9]*\([0-9]*\).*/\1/g' | sed 's/^0//g')
        m=$((M+m))
        h=$((H+h))
        while [ "$m" -ge 60 ]; do
            m=$((m-60))
            h=$((h+1))
        done
        m=$(echo "0$m" | sed 's/^0\([0-9][0-9]$\)/\1/g')
        while [ "$h" -ge 24 ]; do
            h=$((h-24))
        done
        h=$(echo "0$h" | sed 's/^0\([0-9][0-9]$\)/\1/g')
        hm=$h:$m
    fi
    echo " $hm"
}
appointments1(){
    apt1="$(grep "$(date +'%m/%d/%Y')" "$HOME/.calcurse/apts" | sed 's/!/|/g' | sed 's/[^@]*@\ \([0-9]*:[0-9]*\)[^@]*@[^|]*|/\1: /g' | grep "$(date +'%H')" | sed 's/^[0-9][0-9]:[0-9][0-9]:\ //g')"
    apt2="$(calcurse --next | sed '/next.*/d')"
    echo "$apt2" | grep "$apt1" > /dev/null 2>/dev/null && apt1=""
    [ -z "$apt1" ] || apt1="   [ now ] $apt1\n"
    notify-send "📅 Appointment:" "$apt1$apt2\n\n[ middle click to open calcurse. ]"
}
appointments2(){
    st -e calcurse
}

# -----------

# shows the current date
calendar(){ # date
    date +'  %Y-%m-%d'
}
calendar1(){ # mouse-button 1 action for date widget
    notify-send "📅$(date +'%A, %B %d')" "\n$(cal | sed "s/\<$(date +%-d)\>//g")"
}

# -----------

# shows a clock
clock(){ # time
    date +' %H:%M'
}
clock1(){ # mouse-button 1 action for time widget
    notify-send "🕐 $(date +'%H:%M')"
    calendar1
}

# -----------

# shows cpu usage
cpu(){ # cpu
    read -r cpu a b c previdle rest < /proc/stat
    prevtotal=$((a+b+c+previdle))
    sleep 0.5
    read -r cpu a b c idle rest < /proc/stat
    total=$((a+b+c+idle))
    cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))
    echo " $cpu%"
}
cpu1(){ # mouse-button 1 action for cpu widget
    notify-send "$(cpu) cpu"
}

# -----------

# show icon if the CUPS printer service is running
cups(){ # CUPS printer status
    systemctl is-active org.cups.cupsd > /dev/null 2>/dev/null && echo 
}
cups1(){
    notifyservice org.cups.cupsd 🖨
}
cups2(){
    toggleservice org.cups.cupsd
}

# -----------

# uses same icon as memory. Know which one is which.
disk(){ # memory
    usage=$(df -h . | grep -v Filesystem | awk '{print $5}')
    echo " $usage"
}
disk1() { # mouse-button 1 action for memory widget
    notify-send "💾 disk usage: $(df -h "$HOME")"
}

# -----------

# show icon if a gpg key password is currently cached
gpg(){ # cached gpg keys
    gpg-connect-agent 'keyinfo --list' /bye | grep "1 P" > /dev/null 2>/dev/null \
        && echo 
}
gpg1(){ # mouse-button 1 to display cached keys
    key=$(gpg-connect-agent 'keyinfo --list' /bye | grep "1 P" | sed 's/.*KEYINFO\ *\([^\ !]*\).*/\1/g')
    notify-send "🔑 passwords cached for these gpg keys:" "$key\n\n[ middle click to empty cache ]"
}
gpg2(){ # mouse-button 2 to empty gpg password cache
    kill -SIGHUP "$(pidof gpg-agent)"
}


# -----------

# show icon if jupyterhub service is active
jupyterhub(){ # jupyterhub status
    systemctl is-active jupyterhub > /dev/null 2>/dev/null && echo 
}
jupyterhub1(){ # mouse-button 1 action for jupyterhub widget
    notifyservice jupyterhub 🪐
}
jupyterhub2(){
    toggleservice jupyterhub
}

# -----------

# show icon if jellyfin service is active
jellyfin(){ # jupyterhub status
    systemctl is-active jellyfin > /dev/null 2>/dev/null && echo 
}
jellyfin1(){ # mouse-button 1 action for jupyterhub widget
    notifyservice jellyfin 📺
}
jellyfin2(){
    toggleservice jellyfin
}

# -----------

# number of unread emails
email(){ # number of unread emails
    [ -f "$HOME/.msmtprc" ] || return
    if gpg-connect-agent 'keyinfo --list' /bye | grep "1 P" > /dev/null 2>/dev/null;
    then
        num_unread=$(find "$HOME"/.local/share/email/*/INBOX/new/ -type f | wc -l 2> /dev/null)
        echo " $num_unread"
    else
        echo " "
    fi
}
email1(){ # give more email info
    num_unread=$(find "$HOME/.local/share/email/*/INBOX/new/" -type f | wc -l 2> /dev/null)
    if gpg-connect-agent 'keyinfo --list' /bye | grep "1 P" > /dev/null 2>/dev/null;
    then
        notify-send "📧 $num_unread unread emails" "\n[ middle click to sync now. ]\n[  +  + r: sync now      ]"
    else
        notify-send "📧 emails not syncing." "($num_unread unread emails)\n\n[ middle click to unlock gpg key and sync now ]"
    fi
}
email2(){ # start syncing emails
    "$HOME/.scripts/email/syncmail"
}

# -----------

# same info after clicking network icon
localip(){ # local ip address
    nmcli -a | grep inet4 | sed 's/^[^ ]*[ ]\([0-9]*\.[0-9]*\.[0-9]*\.[0-9]*\).*/\1/g' | head -1
}
localip1(){
    network1
}

# -----------

# uses same icon as disk. Know which one is which.
memory(){ # memory
    used=$(free | awk '/Mem/ {print $3 }')
    total=$(free | awk '/Mem/ {print $2 }')
    percentage=$(python -c "print(f'{100*$used/$total:.0f}%')")
    echo " $percentage"
}
memory1() { # mouse-button 1 action for memory widget
    mem=$(free | awk '/Mem/ {printf "%d MiB/%d MiB\n", $3 / 1024.0, $2 / 1024.0 }')
    notify-send "💾 free RAM $mem"
}

# -----------

# shows a clickable globe icon.
network(){
    echo 
}
network1(){
    notify-send "🌐 Network:" "connected to: $(wifi)\nlocal ip:     $(localip)\npublic ip:    $(publicip)"
}

# -----------

# show icon if openconnect is connected
openconnect(){ # openconnect
    pidof openconnect > /dev/null 2>/dev/null && echo   #|| echo ""
}
openconnect1(){ # mouse-button 1 action for openconnect widget
    if pidof openconnect > /dev/null 2>/dev/null; then
       notify-send "🔐 openconnect" "running.\n\n[ middle click to stop ]"
    else
        notify-send "🔐 openconnect" "stopped.\n\n[ middle click to start ]"
    fi
}
openconnect2(){ # mouse-button 1 action for openconnect widget
    pidof openconnect > /dev/null 2>/dev/null && sudo -A killall openconnect
}

# -----------

# show icon if openvpn is connected
openvpn(){ # openvpn
    systemctl is-active openvpn > /dev/null 2>/dev/null && echo   || echo ""
}
openvpn1(){ # mouse-button 1 action for openvpn widget
    notifyservice openvpn 🔐
}
openvpn2(){ # mouse-button 2 action for openvpn widget
    toggleservice openvpn
}

# -----------

# number of updatable packages
pacmanstatus(){ # pacman
    num=$(pacman -Qu | wc -l)
    [ "$num" -gt 0 ] && echo " $num"
}
pacmanstatus1(){ # pacman
    num=$(pacman -Qu | wc -l)
    notify-send "📦 pacman" "$num packages can be updated\n\n[ middle click to update with \"pacman -Syu\" ]"
}
pacmanstatus2(){ # update packages
    sudo -A -p "[sudo] password for 'pacman -Syu'" st -n float -e pacman -Syu
}

# -----------

# status of currently open media player (pause/play)
playercontrol(){ # toggle a service
    # the icon needs to be cached as sometimes playerctl gives Stopped when nothing has happened.
    previous_icon=$(cat "$CACHEDIR/playercontrol") 2> /dev/null
    [ -z "$previous_icon" ] && previous_icon=
    icon=$(timeout 1s playerctl status 2> /dev/null | sed 's/Playing//g' | sed 's/Paused//g' | sed "s/Stopped/$previous_icon/g") || icon=""
    echo "$icon" > "$CACHEDIR/playercontrol"
    echo "$icon"
}
playercontrol1(){ # toggle a service
    timeout 1s playerctl play-pause
    icon1=$(cat "$CACHEDIR/playercontrol")
    [ "$icon1" = "" ] && icon2= && notify-send "⏯"
    [ "$icon1" = "" ] && icon2= && notify-send "⏯"
    echo $icon2 > "$CACHEDIR/playercontrol"
    sed -i "s/$icon1/$icon2/g" "$CACHEDIR/status"
    xsetroot -name "$(cat "$CACHEDIR/status")"
}

# -----------

# introduces lag due to curl call better not to place in status bar.
publicip(){ # local ip address
    curl -s https://ipinfo.io/ip | head -1
}
publicip1(){
    network1
}


# -----------

# clickable icon to start/stop services
services(){ # toggle a service
    echo 
}
services1(){
    dmenu_services
}


# -----------

# show icon if sshd service is active
sshd(){ # ssh daemon
    systemctl is-active sshd > /dev/null 2>/dev/null && echo  # ⛓
}
sshd1(){ # mouse-button 1 action for ssh daemon widget
    notifyservice sshd ⛓
}
sshd2(){
    toggleservice sshd
}

# -----------

# show icon if sshtunnel service is active
sshtunnel(){ # ssh tunnels
    systemctl is-active sshtunnel > /dev/null 2>/dev/null && echo  || echo "" # ⛓
}
sshtunnel1(){ # mouse-button 1 action for ssh tunnel widget
    notifyservice sshtunnel 🔗
}
sshtunnel2(){
    toggleservice sshtunnel
}

# -----------

# show icon if syncthing service is active
syncthing(){ # jupyterhub status
    systemctl is-active syncthing > /dev/null 2>/dev/null && echo 
}
syncthing1(){ # mouse-button 1 action for jupyterhub widget
    notifyservice syncthing 
}
syncthing2(){
    toggleservice syncthing
}

# -----------

# torrenting status
transmission(){
    export PASSWORD_STORE_GPG_OPTS="--pinentry-mode error"
    pidof -s transmission-daemon >/dev/null 2>/dev/null || return
    pass transmission >/dev/null 2>/dev/null
    retval=$?
    [ $retval -eq 2 ] && echo  && return # transmission active but gpg inactive
    if [ $retval -eq 0 ]; then
        username=$(pass show transmission | head -2 | tail -1 | sed 's/^[^:]*:[ ]*//g' )
        password=$(pass show transmission | head -1)
        auth="--auth $username:$password"
    fi
    if ! transmission-remote "$auth" --list \
        | grep -v ID | grep -v Sum:\
        | awk  '{ print $2;}' \
        | sed '/100%/d' | sed 's/%//g' | sed 's|n/a||g' \
        | xargs python -c "from sys import argv; print(f' {sum(int(i) for i in argv[1:])/len(argv[1:]):.0f}%')" 2> /dev/null;
    then
        num=$(transmission-remote "$auth" --list | grep -v ID | grep -vc Sum:)
        [ "$num" -gt 0 ] && echo "🌱$num" && return # seeding
        echo  # active
    fi
}
transmission1(){
    if pass transmission >/dev/null 2>/dev/null; then
        username=$(pass transmission | head -2 | tail -1 | sed 's/^[^:]*:[ ]*//g' )
        password=$(pass transmission | head -1)
        auth="--auth $username:$password"
    fi
    num="$(transmission-remote "$auth" --list | grep -v ID | grep -vc Sum:)"
    title="$(transmission) Transmission: $(transmission | sed 's//active/g' | sed 's/🌱/seeding/g') [$num]"
    msg="\n[ middle click to open transmission-cli   ]\n[ right click to stop transmission-daemon ]"
    [ "$num" -gt 0 ] && msg="\n$(transmission-remote "$auth" --list)\n$msg"
    notify-send "$title" "$msg"
}
transmission2(){
    st -e "$HOME/.local/bin/transmission"
}
transmission3(){
    kill -SIGTERM "$(pidof transmission-daemon)"
}


# -----------

# volume (managed by pulseaudio)
volume(){ # volume
    pct=$(amixer -D pulse get Master | grep "\[on\]" | head -1 | sed "s/^[^\[]*\[\([^%]*\)*%.*/\1/g") || echo 🔇 && return
    [ "$pct" -gt 60 ] && echo "🔊$pct%" && return
    [ "$pct" -gt 20 ] && echo "🔉$pct%" && return
    echo "🔈$pct%"
}
volume1(){ # mouse-button 1 action for volume widget
    icon=$(volume | sed 's/^\(.\).*/\1/g')
    pct=$(volume | sed 's/^.\(.*\)/\1/g' | sed 's/^[ ]*//g')
    notify-send "$icon volume $pct" "\n[  + : volume up   ]\n[  + : volume down ]\n[  +  + : mute    ]"
}

# -----------

# reads from cache! Make sure you have it regularly update somewhere else.
weather(){ # weather
    # reads from cache! Make sure you have it regularly update somewhere else.
    [ -f "$HOME/.cache/weatherreport/short" ] && sed 's/[ ][ ]*/ /g' "$HOME/.cache/weatherreport/short" || echo ""
}
weather1(){ # mouse-button 1 action for weather widget
    # get first 7 lines of weather report and remove all color escape sequences.
    report=$(head -7 "$HOME/.cache/weatherreport/full" | sed 's/\x1b\[[0-9;]*m//g' | tail -n 6 | sed 's/\\/\\\\/g' | sed 's/―/-/g')
    notify-send "⛅ weather" "$(weather)\n$report\n\n[ middle click for full report ]"
}
weather2(){
    st -n float -f mono:12 -g 130x40+1130 -e update_weather --block
}

# -----------

# same info after clicking network icon
wifi(){
    nmcli | grep "connected to" | sed 's/.*connected to //g' | head -1
}
wifi1(){
    network1
}

# -----------

# Status Command
#--------------------------------------------------------------------------------
setstatus
