#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

# start by setting the wallpaper. It's the first thing you notice.
wallpaper current

# start by killing all 'dwm_autostart' processes except this one:
ps aux | grep -ie dwm_autostart | grep -v grep | awk '{print $2}' | sed "/$$/d" | xargs kill -9 &

# save logs here:
LOG="$HOME/.local/share/dwm_autostart.log"
ERR="$HOME/.local/share/dwm_autostart.errors.log"
rm -f "$LOG"; touch "$LOG"
rm -f "$ERR"; touch "$ERR"

log(){
    echo "$@" >> "$LOG"
    eval "$@" >> "$LOG" 2>> "$ERR"
}

start(){
    pidof "$1" >/dev/null 2>&1 && return
    log "$@" &
}

# enable hotkeys
start sxhkd

# notifications
start dunst

# network manager applet
start nm-applet

# bluetooth manager applet
start blueman-applet

# make the mouse invisible after a brief period of not using it.
start unclutter

# enable x settings start
start xsettingsd

# watch monitors and rearrange them on (dis)connection
start watch_screens

# update xrdb database
log xrdb "$HOME/.Xresources"

# export possible screenlayouts and set default one with `arandr`
log default_screenlayout

# conky dashboards (same one on three monitors)
if ! pidof conky >/dev/null 2> /dev/null; then
    log conky -d -x 60
    log conky -d -x -1860
    log conky -d -x -3780
fi

# set cursor speed
# wrapped into loop, as sometimes this inexplicably stops working
while true; do
    log xset r rate 200 45
    sleep 60
done &

# update email inbox every 10 minutes (but only ask once for the password.)
while true; do
    start syncmail
    export PASSWORD_STORE_GPG_OPTS="--pinentry-mode error"
    sleep 600s
done &

# update dwm status bar every 10 seconds
while true; do
    sleep 2s
    start dwm_status
    sleep 8s
done &

# check battery status every 10 minutes
while true; do
    sleep 10s
    start check-low-battery
    sleep 590s
done &

# update weather report every hour
while true; do
    sleep 10s
    start update_weather
    sleep 3590s
done &

# automatically lock screen after 10 minutes (xautolock crashes sometimes -> loop)
while true; do
    sleep 10s
    start xautolock -time 10 -locker validate_and_lock_screen
    sleep 3590s
done &

# enable transparent windows (should be last)
sleep 1
if [ -f "$HOME/.cache/xcs/picom.conf" ]; then
    log picom --daemon --experimental-backends --config "$HOME/.cache/xcs/picom.conf"
else
    log picom --daemon --experimental-backends
fi
