#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#
if [ -z "$2" ] && [ -t 1 ]; then
    highlight -O ansi --force "$1"
elif [ -t 1 ] ; then
    /usr/bin/cat "$@" | highlight -O ansi --force
else
    /usr/bin/cat "$@"
fi
