#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#
# NOTE: this script should be placed in your path such that it takes
#       priority over the nvim binary `/usr/bin/nvim`.

if [ -f /usr/bin/nvr ]; then
     if [ ! $2 ]; then
         if [[ $1 == *".tex" ]]; then
             /usr/bin/nvr --servername 127.0.0.1:9999 $@
             exit 0
         fi
     fi
fi

/usr/bin/nvim $@
