#!/bin/sh
while read file
do
        case "$1" in
        "w") wallpaper "$file" & ;;
        "c")
		[ -z "$destdir" ] && destdir="$(find ~/Pictures -maxdepth 1 -type d | sed "s|$HOME|~|g" | dmenu -p "copy-to-folder" | sed "s|~|$HOME|g")" || exit
		[ -z "$destdir" ] && exit
		[ -d "$destdir" ] || exit
		cp "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file copied to $destdir." &
		;;
        "m")
		[ -z "$destdir" ] && destdir="$(find ~/Pictures -maxdepth 1 -type d | sed "s|$HOME|~|g" | dmenu -p "copy-to-folder" | sed "s|~|$HOME|g")" || exit
		[ -z "$destdir" ] && exit
		[ -d "$destdir" ] || exit
		mv "$file" "$destdir" && notify-send -i "$(readlink -f "$file")" "$file moved to $destdir." &
		;;
	"r")
		convert -rotate 90 "$file" "$file" ;;
	"R")
		convert -rotate -90 "$file" "$file" ;;
	"f")
		convert -flop "$file" "$file" ;;
	"y")
		echo -n "$file" | xclip -selection clipboard &&
		notify-send "$file copied to clipboard" & ;;
	"Y")
		readlink -f "$file" | xclip -selection clipboard &&
			notify-send "$(readlink -f "$file") copied to clipboard" & ;;
	"d")
		[ "$(printf "No\\nYes" | dmenu -i -p "Really delete $file?")" = "Yes" ] && rm "$file" && notify-send "$file deleted." ;;
	"g")	gimp "$file" & ;;
        esac
done
