#!/usr/bin/env bash

IPYTHON=$(which ipython 2> /dev/null)
if [[ $IPYTHON == $HOME/.local/bin/ipython ]]; then
    echo $HOME/.anaconda/bin/ipython $@
    $HOME/.anaconda/bin/ipython $@
else
    echo "you should not get here..."
    echo "ipython: "
    echo $IPYTHON
fi
