#!/usr/bin/env bash

# NOTE: currently, this xdotool script requires vimfx firefox extension

window=$(xdotool getactivewindow)
xdotool key --window $window "Shift+Escape"
xdotool key --window $window o
xdotool key --window $window ctrl+c
xdotool key --window $window Escape
mpv $(xclip -o -sel clip) &> /dev/null

