#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

# if 'nt' is used as option, make terminal non-transparent
if [[ $1 == "nt" ]]; then
    x=1
    shift
    (cat ~/.Xresources && echo *.alpha:1) | xrdb
fi

# run st with default options
/usr/bin/st -f mono:pixelsize=18 $@

# make future terminals transparent again
if [[ $x == 1 ]]; then
    xrdb ~/.Xresources
fi

