#!/bin/bash

if [ -f /etc/systemd/system/openvpn.service ]; then
    if [[ $(systemctl is-active openvpn) == "active" ]]; then
        echo 🔒
        show() {
            notify-send "OpenVPN" "active\n(right click to stop)\n\n$($HOME/.config/i3blocks/openvpn/openvpnstatus)"
        }
        stopp() {
            sudo -A systemctl stop openvpn && /usr/bin/pkill -RTMIN+11 i3blocks 
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) stopp ;;
        esac
    else
        echo "🔓"
        show() {
            notify-send "OpenVPN" "inactive\n(right click to start)\n\n$($HOME/.config/i3blocks/openvpn/openvpnstatus)"
        }
        startt() {
            sudo -A systemctl start openvpn && /usr/bin/pkill -RTMIN+11 i3blocks 
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) startt
        esac
    fi
fi
