#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#
"""
launch mpv over a different random socket each time
"""

import sys
import secrets
from subprocess import Popen


if __name__ == "__main__":
    random_socketname = f"/tmp/mpvsocket{secrets.token_hex(4)}"
    Popen(["/usr/bin/mpv", "--player-operation-mode=pseudo-gui", f"--input-ipc-server={random_socketname}"] + sys.argv[1:])

