#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

if [ -z "$1" ]; then
    echo usage: "mpvcontrol [pause|play|togglepause|toggleplay]"
    exit 1
fi


if [ "$1" = "pause" ]; then
    # pause all mpv (or at least the ones having an active socket file)
    for i in /tmp/mpvsoc*; do
        if echo '{ "command": ["set_property", "pause", true] }' | socat - "$i"; then
            rm "$i" # remove inactive sockets:
        fi
        # save current state to /tmp/mpvstate
        echo "paused" > "$HOME/.cache/mpvstate"
    done
fi

if [ "$1" = "play" ]; then
    # play all mpv (or at least the ones having an active socket file)
    for i in /tmp/mpvsoc*; do
        if echo '{ "command": ["set_property", "pause", false] }' | socat - "$i"; then
            rm "$i" # remove inactive sockets
        fi
        # save current state to /tmp/mpvstate
        echo "playing" > "$HOME/.cache/mpvstate"
    done
fi

if [ "$1" = "togglepause" ] || [ "$1" = "toggleplay" ]; then
    state=$(cat "$HOME/.cache/mpvstate")
    [ "$state" = "paused" ] && mpvcontrol play && exit
    mpvcontrol pause
    exit
fi

