#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

wal -c
wal --backend wal -s -e -a 0.7 -i $HOME/.config/wallpaper.png
cp $HOME/.cache/wal/colors.Xresources $HOME/.Xresources
echo "*.alpha: 0.7" >> $HOME/.Xresources
xrdb $HOME/.Xresources
