#!/bin/sh

guv_dir="$HOME/.local/share/guv"
cwd="$PWD"

if [ ! -d "$guv_dir" ]; then
  mkdir -p "$guv_dir"
fi

if [ "$1" = "activate" ] && [ ! -z "$VIRTUAL_ENV" ]; then
  deactivate
fi

if [ ! -z "$VIRTUAL_ENV" ]; then
  cd "$(dirname $VIRTUAL_ENV)" || return 1
else
  cd "$guv_dir" || return 1
fi

if [ "$1" = "activate" ]; then
  cmd_global="$2/.venv/bin/activate"
  cmd_local="$cwd/.venv/bin/activate"
  cmd_base="base/.venv/bin/activate"
  if [ -f "$cmd_global" ]; then
    . "$cmd_global"
  elif [ -f "$cmd_local" ]; then
    . "$cmd_local"
  elif [ -f "$cmd_base" ]; then
    . "$cmd_base"
  else
    . "$cmd_local" # this will fail but show an error message
  fi
elif [ "$1" = "deactivate" ]; then
  deactivate || true
elif [ "$1" = "install-kernel" ]; then
  if [ -z "$VIRTUAL_ENV" ]; then
    echo "No active environment." > /dev/stderr
    return 1
  fi
  env_name="$(basename `dirname $VIRTUAL_ENV`)"
  python -m ipykernel install --user --name "$env_name" --display-name "$env_name"
else
  echo $PWD
  uv "$@"
fi

cd "$cwd" || return 1
