#!/bin/sh

guv_dir="$HOME/.local/share/guv"
cwd="$PWD"

if [ ! -d "$guv_dir" ]; then
  mkdir -p "$guv_dir"
fi

cd "$guv_dir" || exit

if [ "$1" = "activate" ]; then
  cmd="$2/bin/activate"
  if [ -x "$cmd" ]; then
    . "$cmd"
  fi
  cmd=".venv/bin/activate"
  if [ -x "$cmd" ]; then
    . "$cmd"
  else
    cd "$cwd" || exit
    . $cmd
  fi
elif [ "$1" = "deactivate" ]; then
  deactivate || true
else
  uv "$@"
fi

cd "$cwd" || exit
