#!/bin/sh

guv_dir="$HOME/.local/share/guv"
if [ ! -z "$VIRUTAL_ENV" ]; then
  env_dir = $(dirname $VIRTUAL_ENV)
fi
env_dir="$VIRTUAL_ENV"
cwd="$PWD"

if [ ! -d "$guv_dir" ]; then
  mkdir -p "$guv_dir"
fi

if [ ! -z "$env_dir" ]; then
  cd "$env_dir" || exit
else
  cd "$guv_dir" || exit
fi

if [ "$1" = "activate" ]; then
  cmd_global="$2/.venv/bin/activate"
  cmd_local="$cwd/.venv/bin/activate"
  cmd_base="base/.venv/bin/activate"
  if [ -f "$cmd_global" ]; then
    . "$cmd_global"
  elif [ -f "$cmd_local" ]; then
    . "$cmd_local"
  elif [ -f "$cmd_base" ]; then
    . "$cmd_base"
  else
    . "$cmd_local" # this will fail but show an error message
  fi
elif [ "$1" = "deactivate" ]; then
  deactivate || true
else
  uv "$@"
fi

cd "$cwd" || exit
