#!/usr/bin/env bash
battery=$(acpi -b | grep Discharging | grep ", 5%" 2> /dev/null)
[ ! "$battery" ] && battery=$(acpi -b | grep Discharging | grep ", 4%" 2> /dev/null)
[ ! "$battery" ] && battery=$(acpi -b | grep Discharging | grep ", 3%" 2> /dev/null)
[ ! "$battery" ] && battery=$(acpi -b | grep Discharging | grep ", 2%" 2> /dev/null)
[ ! "$battery" ] && battery=$(acpi -b | grep Discharging | grep ", 1%" 2> /dev/null)
[ ! "$battery" ] && battery=$(acpi -b | grep Discharging | grep ", 0%" 2> /dev/null)
[ ! "$battery" ] && exit 1
notify-send "Battery Low" "$battery" -u critical
exit 0
