---
# Ansible Galaxy requirements
# Install with: ansible-galaxy collection install -r requirements.yml

collections:
  - name: community.general
    version: ">=8.0.0"

  - name: kewlfft.aur
    version: ">=1.0.0"
