#!/bin/bash

if [[ $(systemctl is-active openvpn) == "active" ]]; then
    echo 🔒
    show() {
        #$HOME/.scripts/non-transparent-terminal -n topenvpn -f mono:pixelsize=18 -e $HOME/.config/i3blocks/openvpn/openvpnstatus;
        notify-send "OpenVPN" "active\n(right click to stop)\n\n$($HOME/.config/i3blocks/openvpn/openvpnstatus)"
    }
    stopp() {
        $HOME/.scripts/non-transparent-terminal -n topenvpn -f mono:pixelsize=18 -e $HOME/.config/i3blocks/openvpn/stop;
    }
    case $BLOCK_BUTTON in
        1) show ;;
        3) stopp ;;
    esac
else
    echo "🔓"
    show() {
        #$HOME/.scripts/non-transparent-terminal -n topenvpn -f mono:pixelsize=18 -e $HOME/.config/i3blocks/openvpn/openvpnstatus;
        notify-send "OpenVPN" "inactive\n(right click to start)\n\n$($HOME/.config/i3blocks/openvpn/openvpnstatus)"
    }
    startt() {
        $HOME/.scripts/non-transparent-terminal -n topenvpn -f mono:pixelsize=18 -e  $HOME/.config/i3blocks/openvpn/start;
    }
    case $BLOCK_BUTTON in
        1) show ;;
        3) startt
    esac
fi

