#!/usr/bin/python3
""" Open as webapp """

# imports
import os
import sys
import argparse
import subprocess

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("address", help="web adress to open as webapp")
    args = parser.parse_args()
    return args

def exists(browser):
    if not browser:
        return False
    with open(os.devnull, "w") as out:
        browser_exists = not subprocess.call(["which", browser], stdout=out, stderr=out)
    return browser_exists

def parse_address(address):
    if not address.startswith("http://") and not address.startswith("https://"):
        while "//" in address:
            address = address.replace("//","/")
        address = address if os.path.exists(address) else f"http://{address}"
    while "///" in address:
        address = address.replace("///","//")
    if not address.startswith("http://") and not address.startswith("https://"):
        address = f"file:///{address}"
    return address

def run_and_exit(command):
    print(" ".join(command))
    with open(os.devnull, "w") as out:
        subprocess.Popen(command, stdout=out, stderr=out)
    exit()


if __name__ == "__main__":
    args = parse_args()
    address = parse_address(args.address)

    if exists("chromium"):
        run_and_exit(["chromium", f"--app={address}"])

    if exists("firefox"):
        run_and_exit(["firefox", f"--new-window", address])

    browser = os.environ.get("BROWSER")
    if exists(browser):
        run_and_exit([browser, address])

