#!/usr/bin/env bash
mkdir -p ~/.cache
curl -s wttr.in > ~/.cache/weatherreport
printf "%s" "$(sed '16q;d' ~/.cache/weatherreport | grep -wo "[0-9]*%" | sort -n | sed -e '$!d' | sed -e "s/^/☔ /g" | tr -d '\n')" > ~/.cache/weatherreportshort
sed '13q;d' ~/.cache/weatherreport | grep -o "m\\(-\\)*[0-9]\\+" | sort -n -t 'm' -k 2n | sed -e 1b -e '$!d' | tr '\n|m' ' ' | awk '{print "  ",$1 "°","",$2 "°"}' | sed s/☔//g >> ~/.cache/weatherreportshort
dwm_status
cat ~/.cache/weatherreportshort
cat ~/.cache/weatherreport

if [[ $1 == "--block" ]]; then
    read
fi
