#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#
"""
Open a file in a chromium app window inside jupyterhub

Args:
    $1: The path of the file to open.

Note:
    Requires a jupyterhub instance running at port 8000.
"""

# Imports

import os
import sys
import uuid
import getpass
from subprocess import Popen


# Constants

USER = getpass.getuser()
HOME = os.path.expanduser("~")
PATH = "" if len(sys.argv) < 2 else os.path.abspath(os.path.expanduser(sys.argv[1]))

# Functions

def open_url(url):
    """ Open a url with chromium app

    Args:
        url: the url to open
    """
    Popen(["webapp", url])

def open_with_jupyterhub(abspath):
    """ Create a new jupyterhub workspace and open file in that workspace

    Args:
        abspath: the absolute path of the file to open

    Note:
        this function requires a jupyterhub instance running at port 8000.
    """
    id = uuid.uuid4().hex[:4]
    relpath = abspath.replace(HOME, "")
    open_url(f"localhost:8000/user/{USER}/lab/workspaces/{id}/tree/{relpath}")


# Run program

if __name__ == "__main__":
    # first check if the requested path exists
    if PATH != "" and not os.path.exists(PATH):
        print("requested path does not exist. exiting.")
        exit(1)

    # if the path exists, open it:
    open_with_jupyterhub(PATH)

