#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

# Imports
import os
import time
import sys, tty, termios
import ueberzug.lib.v0 as ueberzug
import subprocess


X = 0
if len(sys.argv) > 2:
    X = int(sys.argv[2])

Y = 0
if len(sys.argv) > 3:
    Y = int(sys.argv[3])

WX=100
if len(sys.argv) > 4:
    WX = int(sys.argv[4])

WY=WX//2
if len(sys.argv) > 5:
    WY = int(sys.argv[5])

# Functions
def wait_for_any_input():
    """ from https://stackoverflow.com/questions/510357/python-read-a-single-character-from-the-user"""
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(sys.stdin.fileno())
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    print(ch)

def draw(path, x, y, wx, wy):
    with ueberzug.Canvas() as c:
        demo = c.create_placement('ueberzug', x=x, y=y, width=wx, height=wy, scaler="contain")
        demo.path = path
        demo.visibility = ueberzug.Visibility.VISIBLE
        wait_for_any_input()

def show_svg(path):
    with open(os.devnull, "w") as devnull:
        subprocess.call(["inkscape", path, "-e", "/tmp/ubz.png"], stdout=devnull, stderr=devnull)
    subprocess.call(["ubz", "/tmp/ubz.png"])


if __name__ == "__main__":
    path = sys.argv[1]
    if path.endswith(".svg"):
        show_svg(path)
        exit(0)
    draw(path, X, Y, WX, WY)
