#!/usr/bin/python3
import os
import sys
import subprocess

try:
    filename = os.path.abspath(os.path.expanduser(sys.argv[1]))
except IndexError:
    exit(1)


if filename.lower().endswith(".fsp"):
    exit(subprocess.call(["/opt/lumerical/2019b/bin/fdtd-solutions", filename]))

if filename.lower().endswith(".gds"):
    exit(subprocess.call(["/usr/bin/klayout", "-e", filename]))

if filename.lower().endswith(".icp"):
    exit(subprocess.call(["/opt/lumerical/2019b/bin/interconnect-app", "-e", filename]))
