#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

try:
    import os
    import sys
    from subprocess import call, Popen, PIPE

    TEMPLATE = """To: EMAIL
From: EMAIL
Subject: SUBJECT

CONTENT
    """

    RC_TEMPLATE = """
# No account for email {email} detected. Please edit this file to configure.
# Just exit this file if you do not want to configure anything.
account ALIAS
from EMAIL
host SMTPHOST
port PORT
tls TLSONOFF
auth AUTHONOFF
user USER_DELETE_IF_NO_SPECIAL_USERNAME
password PASSWORD
    """

    with open(os.path.expanduser("~/.msmtprc"), "r") as file:
        RC = file.read()

    if sys.stdin.isatty():
        with open("/tmp/mail", "w") as file:
            file.write(TEMPLATE)

        call([os.environ.get("EDITOR"), "/tmp/mail"])

        with open("/tmp/mail", "r") as file:
            content = file.read()
    else:
        content = sys.stdin.read()

    if content == TEMPLATE:
        print("no mail sent")
        exit()

    to = content.splitlines()[0].split(":")[1].strip()
    frm = content.splitlines()[1].split(":")[1].strip()

    if frm not in RC:
        with open("/tmp/msmtprc", "w") as file:
            file.write(RC_TEMPLATE.format(email=frm))
        call([os.environ.get("EDITOR"), "/tmp/msmtprc"])
        with open("/tmp/msmtprc", "r") as file:
            extra_rc_content = file.read()
            if extra_rc_content == RC_TEMPLATE:
                print("no mail sent")
                exit()
            else:
                extra_rc_content = "\n".join(
                    [
                        line
                        for line in extra_rc_content.splitlines()
                        if not line.startswith("#")
                    ]
                )
                extra_rc_content = "# {}\n".format(frm) + extra_rc_content
                with open(os.path.expanduser("~/.msmtprc"), "a") as file:
                    file.write(extra_rc_content)

    email = Popen(["printf", content], stdout=PIPE).stdout
    status = call(["msmtp", "--read-envelope-from", to], stdin=email)

    if status == 0:
        print("mail sent")
    else:
        print("no mail sent")
except:
    print("no mail sent")
