#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

echo2(){>&2 echo $@;}

[[ ! -z $1 ]] && FILENAME=$1 || exit 1
[[ ! -z $2 ]] && LINES=$2 || LINES=51

if [[ $FILENAME == *.png ]]; then
    ubz $FILENAME
fi

# all other files:
head --lines=$LINES $FILENAME | highlight -O ansi --force
exit $?
