#!/bin/bash

if [ -f /etc/systemd/system/sshtunnel.service ]; then
    if [[ $(systemctl is-active sshtunnel) == "active" ]]; then
        echo 🔗
        show() {
            #$HOME/.scripts/non-transparent-terminal -n tsshtunnel -f mono:pixelsize=18 -e $HOME/.config/i3blocks/sshtunnel/sshtunnelstatus;
            notify-send "sshtunnel" "active\n(right click to stop)\n\n$($HOME/.config/i3blocks/sshtunnel/sshtunnelstatus)"
        }
        stopp() {
            $HOME/.scripts/non-transparent-terminal -n tsshtunnel -f mono:pixelsize=18 -e $HOME/.config/i3blocks/sshtunnel/stop;
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) stopp ;;
            #3) pkill -f tsshtunnel
        esac
    else
        echo "❌"
        show() {
            #$HOME/.scripts/non-transparent-terminal -n tsshtunnel -f mono:pixelsize=18 -e $HOME/.config/i3blocks/sshtunnel/sshtunnelstatus;
            notify-send "sshtunnel" "inactive\n(right click to start)\n\n$($HOME/.config/i3blocks/sshtunnel/sshtunnelstatus)"
        }
        startt() {
            $HOME/.scripts/non-transparent-terminal -n tsshtunnel -f mono:pixelsize=18 -e $HOME/.config/i3blocks/sshtunnel/start;
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) startt ;;
        esac
    fi
fi
