#!/usr/bin/env bash

# name of ueberzug tempfile:
export FZF_UBZ_FIFO="$(mktemp --dry-run --suffix "fzf-ubz-$$")"

# Open Ueberzug fifo:
mkfifo "${FZF_UBZ_FIFO}"
<"${FZF_UBZ_FIFO}" \
ueberzug layer --parser bash --silent &
# prevent EOF
3>"${FZF_UBZ_FIFO}" \
exec

# Execute FZF
SHELL="/bin/bash" \
    /usr/bin/fzf \
        "${@}"
exit_code=$?

# Close Ueberzug fifo
3>&- \
    exec
&>/dev/null \
    rm "${FZF_UBZ_FIFO}"
&>/dev/null \
    kill $(jobs -p)

# make sure ueberzug is closed
killall ueberzug 2> /dev/null
rm -f $FZF_UBZ_FIFO

# exit with status of FZF command
exit $exit_code

