#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

PREVIEW=""

[[ ! -z $1 ]] && FILENAME=$1 || exit 1
[[ ! -z $2 ]] && LINESSHOWN=$2 || LINESSHOWN=51

# dummy ueberzug preview (note that path is empty -> no preview):
< <(</dev/tty stty size) read TERMINAL_LINES TERMINAL_COLUMNS
>"${FZF_UBZ_FIFO}" declare -A -p cmd=( \
    [action]=add [identifier]="preview" \
    [x]="0" [y]="0" \
    [width]="${FZF_PREVIEW_COLUMNS}" [height]="${FZF_PREVIEW_LINES}" \
    [scaler]=forced_cover [scaling_position_x]=0.5 [scaling_position_y]=0.5 \
    [path]="")


if [ ! -d $FILENAME ] 2> /dev/null && [ ! -f "$FILENAME" ] 2> /dev/null; then
    printf "$FILENAME"
    exit
fi

if [ -d "$FILENAME" ] 2> /dev/null; then
    tree -L 1 $FILENAME
    exit
fi

if [[ $FILENAME == *.py ]]; then
    cat $FILENAME | highlight --src-lang=python -O ansi --force 2> /dev/null || echo $FILENAME
    exit
fi

if [[ $FILENAME == *.ipynb ]]; then
    jupyter nbconvert $FILENAME --to python --stdout 2> /dev/null | highlight -O ansi --force 2> /dev/null || echo "$FILENAME"
    exit
fi

if [[ $FILENAME == *.htm* ]]; then
    cat $FILENAME | highlight --src-lang=html -O ansi --force 2> /dev/null || echo $FILENAME
    exit
fi

if [[ $FILENAME == *.md ]]; then
    cat $FILENAME | highlight --src-lang=markdown -O ansi --force 2> /dev/null || echo $FILENAME
    exit
fi

if [[ $FILENAME == *.pdf ]]; then
    pdftotext -q "$FILENAME" - 2> /dev/null || echo $FILENAME
    exit
fi

if [[ $FILENAME == *.bash ||  $FILENAME == *.sh ]]; then
    cat $FILENAME | highlight --src-lang=bash -O ansi --force 2> /dev/null || echo $FILENAME
    exit
fi

if [[ $FILENAME == *.png || $FILENAME == *.jpg || $FILENAME == *.jpeg || $FILENAME == *.svg || $FILENAME == *.mp4 ]]; then
    echo $FILENAME
    [[ $FILENAME == *.mp4 ]] && ffmpeg -y -i $FILENAME -ss 00:00:01.000 -vframes 1 /tmp/fzf-ubz-preview.png &> /dev/null && FILENAME=/tmp/fzf-ubz-preview.png
    [[ $FILENAME == *.svg ]] && inkscape "$FILENAME" -e /tmp/fzf-ubz-preview.png &> /dev/null && FILENAME=/tmp/fzf-ubz-preview.png
    # ueberzug preview:
    < <(</dev/tty stty size) read TERMINAL_LINES TERMINAL_COLUMNS
    X=$((TERMINAL_COLUMNS - FZF_PREVIEW_COLUMNS - 3))
    Y=$((TERMINAL_LINES - FZF_PREVIEW_LINES - 1))
    [ "$FZF_UBZ_LINE" -lt "$Y" ] 2> /dev/null && Y="$FZF_UBZ_LINE"
    >"${FZF_UBZ_FIFO}" declare -A -p cmd=( \
        [action]=add [identifier]="preview" \
        [x]="${X}" [y]="${Y}" \
        [width]="${FZF_PREVIEW_COLUMNS}" [height]="${FZF_PREVIEW_LINES}" \
        [scaler]=forced_cover [scaling_position_x]=0.5 [scaling_position_y]=0.5 \
        [path]="${FILENAME}")
    exit
fi

# if all else fails:
printf "$FILENAME"

