#!/bin/bash

if [ -f /etc/systemd/system/sshtunnel.service ]; then
    if [[ $(systemctl is-active sshtunnel) == "active" ]]; then
        echo 🔗
        show() {
            notify-send "sshtunnel" "active\n(right click to stop)\n\n$($HOME/.config/i3blocks/sshtunnel/sshtunnelstatus)"
        }
        stopp() {
            sudo -A systemctl stop sshtunnel && /usr/bin/pkill -RTMIN+13 i3blocks 
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) stopp ;;
            #3) pkill -f tsshtunnel
        esac
    else
        echo "❌"
        show() {
            notify-send "sshtunnel" "inactive\n(right click to start)\n\n$($HOME/.config/i3blocks/sshtunnel/sshtunnelstatus)"
        }
        startt() {
            sudo -A systemctl start sshtunnel && /usr/bin/pkill -RTMIN+13 i3blocks 
        }
        case $BLOCK_BUTTON in
            1) show ;;
            3) startt ;;
        esac
    fi
fi
