#!/usr/bin/env bash

# wrapper script around xcs, just to change alpha values

usage(){
    >&2 echo usage: alpha: get and set transparency of windows [-h] {get,set} [value]
    exit 1
}

command="$1"
value="$2"

if [ "$command" = "get" ]; then
   xcs --alpha
   exit $?
fi

if [ "$command" = "set" ]; then
   xcs --alpha "$value"
   exit $?
fi

usage
