#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

usage(){
    >&2 echo "usage: xcs [ --alpha <value> ] <colorscheme>"
}

available_colorschemes(){
    echo
    echo
    echo available colorschemes [in \~/.config/Xresources]:
    cd ~/.config/Xresources
    find . -executable | sed s/[.]//g | sed s/[/]//g | sed '/^[[:space:]]*$/d'
}

if [ -z "$1" ]; then
    cd ~/.config/Xresources
    cs=$(find . -executable | sed s/[.]//g | sed s/[/]//g | sed '/^[[:space:]]*$/d' | dmenu -p "select colorscheme" -i -l 20)
fi


if [ "$1" = "-a" ] || [ "$1" = "--alpha" ]; then
    shift
    alpha=$1
    shift
fi

if [ "$1" = "ls" ]; then
    available_colorschemes
    exit 0
fi

if [ -z "$cs" ]; then
    if [ -z "$1" ]; then
        usage
        available_colorschemes
        exit 1
    fi
    cs=$1
fi

rm -f ~/.Xresources
cp ~/.config/Xresources/$cs ~/.Xresources

if [ $alpha ]; then
    echo *.alpha: $alpha >> ~/.Xresources
fi

xrdb ~/.Xresources 2> /dev/null
dwm_status
