#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

usage(){
    >&2 echo "usage: xcs [ --alpha <value> ] <colorscheme>"
}

available_colorschemes(){
    echo
    echo
    echo available colorschemes [in \~/.config/Xresources]:
    cd ~/.config/Xresources
    find . -executable | sed s/[.]//g | sed s/[/]//g
}

if [ ! $1 ]; then
    usage
    available_colorschemes
    exit 1
fi

if [ $1 = "-a" ] || [ $1 = "--alpha" ]; then
    shift
    alpha=$1
    shift
fi

if [ ! $1 ]; then
    usage
    available_colorschemes
    exit 1
fi

if [ $1 = ls ]; then
    available_colorschemes
    exit 0
fi

rm -f ~/.Xresources
cp ~/.config/Xresources/$1 ~/.Xresources

if [ $alpha ]; then
    echo *.alpha: $alpha >> ~/.Xresources
fi

xrdb ~/.Xresources 2> /dev/null
dwm_status
