#!/usr/bin/env bash
passlines=$(grep PassCmd $HOME/.mbsyncrc)
if [ ! -z "$passlines" ]; then
    passline=$(printf "$passlines" | head -1)
    passcmd=$(echo $passline | sed 's/.*"\(.*\).*"/\1/g')
    [ -z "$passcmd" ] && passcmd=$(echo $passline | sed "s/.*\'\(.*\).*\'/\1/g")
    $passcmd > /dev/null
    exit_code=$?
    if [ $exit_code -ne 0 ]; then
        >&2 echo "syncmail failed!"
        >&2 echo "could not decrypt passwords."
        exit $exit_code
    fi
fi

[ -d $HOME/.local/share/email ] || (>&2 echo "email directory '$HOME/.local/share/email' does not exist" && exit 1)

echo "syncing emails..."
num_unread1=$(find $HOME/.local/share/email/*/INBOX/new/ -type f | wc -l 2> /dev/null)
mbsync --all &> /dev/null
notmuch new  &> /dev/null
num_unread2=$(find $HOME/.local/share/email/*/INBOX/new/ -type f | wc -l 2> /dev/null)

new_mail=$(python -c "print($num_unread2-$num_unread1)")
if [ "$new_mail" -eq 0 ]; then
    echo "no new email."
elif [ "$new_mail" -eq 1 ]; then
    notify-send "syncmail:" "$new_mail new unread email."
    echo "$new_mail new unread email."
else
    notify-send "syncmail:" "$new_mail new unread emails."
    echo "$new_mail new unread emails."
fi

dwm_status

exit $exit_code
