#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

# merge pdfs with ghostscript
gsmerge(){
    output="$1"
    shift 1
    gs \
     -sOutputFile="$output" \
     -sDEVICE=pdfwrite \
     -dCompatibilityLevel=1.4 \
     -dNOPAUSE \
     -dBATCH \
     -dAutoRotatePages=/None \
    "$@"
}

# handle output argument
[ -z "$1" ] && (>&2 echo usage: pdfmerge [merged pdf] [pdf1 pdf2 pdf3 ...] && exit 1) || output=$(echo "$1" | sed 's/^\(.*\).pdf/\1/g').pdf

# handle input arguments
shift 1
args=$(for var in "$@"; do
    printf "\"$(echo "$var" | sed 's/^\(.*\).pdf/\1/g').pdf\" "
done)

gsmerge "$output" "$args"

