#!/usr/bin/python3

"""process_wallpaper

adapted from fhttps://github.com/anirudhajith/process-wallpaper

"""

import io
import os
import sys
import json
import re, sys
from PIL import Image
from wordcloud import WordCloud
import subprocess

configJSON = {
    "resolution": {"height": 1080, "width": 1920},
    "wordcloud": {"background": "#101010", "margin": 20},
}

assert len(sys.argv) == 1, "No arguments expected"

commandList = []

topOutput = subprocess.check_output(["top", "-b", "-n", "1"]).decode().split("\n")[7:]

for line in topOutput[:-1]:
    line = re.sub(r"\s+", " ", line).strip()
    fields = line.split(" ")

    try:
        if fields[11].count("/") > 0:
            command = fields[11].split("/")[0]
        else:
            command = fields[11]

        cpu = float(fields[8].replace(",", "."))
        mem = float(fields[9].replace(",", "."))

        if command != "top":
            commandList.append((command, cpu, mem))
    except:
        pass


commandDict = {}

for command, cpu, mem in commandList:
    if command in commandDict:
        commandDict[command][0] += cpu
        commandDict[command][1] += mem
    else:
        commandDict[command] = [cpu + 1, mem + 1]

resourceDict = {}

for command, [cpu, mem] in commandDict.items():
    resourceDict[command] = (cpu ** 2 + mem ** 2) ** 0.5


wc = WordCloud(
    background_color=configJSON["wordcloud"]["background"],
    width=int(
        configJSON["resolution"]["width"] - 2 * configJSON["wordcloud"]["margin"]
    ),
    height=int(
        configJSON["resolution"]["height"] - 2 * configJSON["wordcloud"]["margin"]
    ),
).generate_from_frequencies(resourceDict)

wordcloud = wc.to_image()
wallpaper = Image.new(
    "RGB",
    (configJSON["resolution"]["width"], configJSON["resolution"]["height"]),
    configJSON["wordcloud"]["background"],
)
wallpaper.paste(
    wordcloud, (configJSON["wordcloud"]["margin"], configJSON["wordcloud"]["margin"])
)

wallpaper.save(os.path.expanduser("~/.config/wallpaper.png"))
subprocess.call(["set_wallpaper", os.path.expanduser("~/.config/wallpaper.png")])
subprocess.call(
    [
        "convert",
        "-quality",
        "100",
        "-negate",
        os.path.expanduser("~/.config/wallpaper.png"),
        os.path.expanduser("~/.config/lockscreen.png"),
    ]
)
