#!/usr/bin/env python
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

with open("/proc/asound/cards", "r") as file:
    content = "\n" + file.read()

card = int(content.split("[PCH")[0].split("\n")[-1].strip())

print(card)
