#!/bin/sh

pandoc=$(which pandoc 2> /dev/null)

if [ -x "$pandoc" ]; then
    cat - \
        | "$pandoc" --from markdown --to markdown \
        | sed 's/-   \[ \]/- \[ \]/g' \
        | sed 's/-   \\\[ \\\]/- \[ \]/g' \
        | sed 's/-   \\\[\.\\\]/- \[\.\]/g' \
        | sed 's/-   \\\[o\\\]/- \[o\]/g' \
        | sed 's/-   \\\[O\\\]/- \[O\]/g' \
        | sed 's/-   \[x\]/- \[X\]/g' \

    exit 0
fi

cat -
exit 1
