#!/usr/bin/env bash
# leader=$(grep "mapleader" $HOME/.config/nvim/init.vim | sed 's|.*=\ *\(.*\)\ *|\1|g' | sed 's/"//g' | sed s/\'//g )
cmd=$(cat $HOME/.config/nvim/init.vim $HOME/.config/nvim/plugins.vim \
  | grep nnoremap | grep : \
  | grep -v mapleader | grep -v autocmd | grep -v "; :"\
  | sed '/^\ .*/d' | sed '/^".*/d' | sed '/^let.*/d' \
  | sed 's/nnoremap//g' | sed 's/<Esc>//g' | sed 's/<CR>//g' \
  | sort \
  | dmenu \
  | sed 's/^.*:\([^<]*\).*$/\1/g')
exit_code=$?
printf "$cmd"
exit $exit_code
