#!/usr/bin/python

# imports
import os
import sys
import shutil
from subprocess import call, check_output, CalledProcessError, Popen, PIPE

# Constants
IMGDIR = "img"

# script
if __name__ == "__main__":
    try:
        s_orig = s = check_output(["xclip", "-selection", "primary", "-o"]).decode()[:-1].strip()
    except CalledProcessError:
        print(s_orig)
        exit(1)

    if not s.split(" ![")[0].startswith("[") or not s.split(") ")[-1].endswith(")"):
        print(s_orig)
        exit(1)

    try:
        s_list = s.split("](")
        name = s_list[0]
        name = name[1:].strip()
        url = s_list[1]
        url = url[:-1].strip()
        if url == "":
            try:
                url = check_output(["xclip", "-selection", "clipboard", "-o"]).decode()[:-1].strip()
            except CalledProcessError:
                print(s_orig)
                exit(1)

    except IndexError:
        print(s_orig)
        exit(1)
    path = os.path.join(IMGDIR, name)

    # check if path exists
    if os.path.exists(path):
        print(s_orig)
        exit(1)

    # create image folder if it does not exist
    if not os.path.isdir(IMGDIR):
        os.mkdir(IMGDIR)

    # download file
    if not url.startswith("http"):
        try:
            shutil.copy(url, path)
        except:
            print(s_orig)
            exit(1)
    else:
        with open(os.devnull) as NULL:
            status = call(["curl",url,"--output",path], stdout=NULL, stderr=NULL)
        if status != 0:
            print("could not download image file")
            exit(status)

    s = f"[{name}]({path})"
    print(s)
