#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

if [ ! -d "$HOME/VimWiki" ]; then
    mkdir "$HOME/VimWiki"
fi


cd "$HOME/VimWiki" || exit 1

if [ ! -z "$1" ]; then
    if [ "$1" = "git" ]; then
        if [ "$2" = "push" ]; then
            git add -A
            git commit -m "updated $(git status -s | grep ".md$" | sed 's/^...//g' | sed 's/.md$/, /g' | tr -d '\n' | sed 's/, $//g')"
        fi
        eval "$@"
        exit $?
    fi
    if [ "$1" = "today" ] || [ "$1" = "w" ]; then
        filename="diary/$(date +'%Y-%m-%d').md"
    elif [ "$1" = "tomorrow" ] || [ "$1" = "m" ]; then
        filename="diary/$(date +'%Y-%m-%d' --date=tomorrow).md"
        echo "$filename"
    elif [ "$1" = "yesterday" ] || [ "$1" = "y" ]; then
        filename="diary/$(date +'%Y-%m-%d' --date=yesterday).md"
    elif [ "$1" = "diary" ] || [ "$1" = "i" ]; then
        if [ -z "$2" ]; then
            filename=diary/diary.md
        else
            filename=$(find diary -type f -name "*$2*" | head -1)
            if [ -z "$filename" ]; then
                filename=$(date +'%Y-%m-%d' --date="$2" 2> /dev/null) || exit 1
                filename="diary/$filename.md"
            fi
        fi
    else
        filename=$(find . -type f -name "*$1*" | head -1)
    fi
    /usr/bin/nvim -c VimwikiIndex -c 'Git pull' -c "execute \"e $filename\""
    exit
fi

/usr/bin/nvim -c VimwikiIndex -c 'Git pull'
