#!/usr/bin/env bash

message() {
    if [ $1 ]; then
        notify-send "$3 $2" "success!"
    else
        notify-send "$3 $2" "failed."
    fi
}

service=$(ls /etc/systemd/system/ | dmenu -l 20 -p "select service" $@)


if [ ! $service ]; then
    message "" "no service selected" ""
    exit 1
fi


if [[ $(systemctl is-active $service) == "active" ]]; then
    sudo -A systemctl stop $service
    message $? $service "stop"
    ~/.config/dwm/status.sh
else
    sudo -A systemctl restart $service;
    message $? $service "start"
    ~/.config/dwm/status.sh
fi
