#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

prompt="[sudo] password for $USER"
if [ $1 ]; then
    prompt=$1;
fi

echo -n "" | dmenu -p "$prompt" -nb "$color15" -nf "$color15" -sb "$color2" -sf "$color15" -fn monospace-22
