#!/bin/sh
cat <<EOF | xmenu | sh &
Applications
	IMG:./web.png  Web Browser	firefox
	IMG:./gimp.png Image editor	gimp
Terminal (xterm)	xterm
Terminal (urxvt)	urxvt
Terminal (st)	st

Shutdown	poweroff
Reboot	reboot
EOF