vim.api.nvim_set_hl(0, 'Normal', { bg = 'none' })
vim.api.nvim_set_hl(0, 'NormalFloat', { bg = 'none' })

-- TreeSitter
vim.api.nvim_set_hl(0, 'Special', { ctermfg = 5 })
vim.api.nvim_set_hl(0, 'TSKeywordFunction', { bold = true, ctermfg = 14 })
-- vim.api.nvim_set_hl(0, "link", { TSKeywordReturn TSKeywordFunction})
vim.api.nvim_set_hl(0, 'PreProc', { ctermfg = 6 })
vim.api.nvim_set_hl(0, 'Constant', { ctermfg = 10 })
vim.api.nvim_set_hl(0, 'Identifier', { ctermfg = 12 })
vim.api.nvim_set_hl(0, 'Type', { italic = true, ctermfg = 4 })
vim.api.nvim_set_hl(0, 'Statement', { bold = true, ctermfg = 11 })
vim.api.nvim_set_hl(0, 'Delimiter', { bold = true, ctermfg = 7 })

-- QuickScope
vim.api.nvim_set_hl(0, 'QuickScopePrimary', { bold = true, ctermfg = 4 })

-- TUI
vim.api.nvim_set_hl(0, 'Search', { ctermfg = 15, ctermbg = 6 })
vim.api.nvim_set_hl(0, 'IncSearch', { bold = true, ctermfg = 15, ctermbg = 6 })
vim.api.nvim_set_hl(0, 'ColorColumn', { ctermbg = 4 })
vim.api.nvim_set_hl(0, 'DiffAdd', { ctermbg = 4 })
vim.api.nvim_set_hl(0, 'DiffChange', { ctermbg = 5 })
vim.api.nvim_set_hl(0, 'DiffDelete', { bold = true, ctermfg = 4, ctermbg = 6 })
vim.api.nvim_set_hl(0, 'DiffText', { bold = true, ctermbg = 9 })
vim.api.nvim_set_hl(0, 'Directory', { ctermfg = 6 })
vim.api.nvim_set_hl(0, 'Error', { bold = true, ctermfg = 1, ctermbg = 'none' })
vim.api.nvim_set_hl(0, 'ErrorMsg', { bold = true, ctermfg = 15, ctermbg = 9 })
vim.api.nvim_set_hl(0, 'FoldColumn', { ctermfg = 8, ctermbg = 'none' })
vim.api.nvim_set_hl(0, 'Folded', { ctermfg = 'none', ctermbg = 8 })
vim.api.nvim_set_hl(0, 'Ignore', { ctermfg = 8 })
vim.api.nvim_set_hl(0, 'LineNr', { ctermfg = 3 })
vim.api.nvim_set_hl(0, 'MatchParen', { ctermfg = 3 })
vim.api.nvim_set_hl(0, 'ModeMsg', { ctermfg = 1 })
vim.api.nvim_set_hl(0, 'MoreMsg', { ctermfg = 2 })
vim.api.nvim_set_hl(0, 'NonText', { bold = true, ctermfg = 4 })
vim.api.nvim_set_hl(0, 'Question', { ctermfg = 2 })
vim.api.nvim_set_hl(0, 'SignColumn', { ctermbg = 'none' })
vim.api.nvim_set_hl(0, 'SpecialKey', { ctermfg = 2 })
vim.api.nvim_set_hl(0, 'SpellBad', { bold = true, ctermfg = 9, ctermbg = 'none' })
vim.api.nvim_set_hl(0, 'SpellCap', { underline = true, ctermfg = 9, ctermbg = 'none' })
vim.api.nvim_set_hl(0, 'SpellErrors', { underline = true, ctermfg = 1, ctermbg = 'none' })
vim.api.nvim_set_hl(0, 'SpellLocal', { underline = true, ctermfg = 9, ctermbg = 'none' })
vim.api.nvim_set_hl(0, 'SpellRare', { underline = true, ctermfg = 9, ctermbg = 'none' })
-- vim.api.nvim_set_hl(0, 'StatusLine', { bold = true, reverse = true })
-- vim.api.nvim_set_hl(0, 'StatusLineNC', { reverse = true })
vim.api.nvim_set_hl(0, 'Title', { bold = true, ctermfg = 10 })
vim.api.nvim_set_hl(0, 'Todo', { ctermfg = 7, ctermbg = 2 })
vim.api.nvim_set_hl(0, 'Underlined', { underline = true, ctermfg = 12 })
vim.api.nvim_set_hl(0, 'VertSplit', { ctermbg = 'none' })
-- vim.api.nvim_set_hl(0, 'Visual', { reverse = true })
vim.api.nvim_set_hl(0, 'Warning', { ctermfg = 7, ctermbg = 3 })
vim.api.nvim_set_hl(0, 'WarningMsg', { ctermfg = 15, ctermbg = 3 })
vim.api.nvim_set_hl(0, 'WildMenu', { ctermfg = 0, ctermbg = 3 })

vim.api.nvim_set_hl(0, 'LspInlayHint', { italic = true, ctermfg = 8 })
