#!/usr/bin/python3

# imports
import os
import sys
import gi; gi.require_version("Gtk", "3.0")
from gi.repository import Gtk
from getpass import getpass

# dialog
class AskPassDialog(Gtk.Dialog):
    def __init__(self):
        Gtk.Dialog.__init__(
            self,
            "Password",
            None,
            0,
        )

        self.set_default_size(150, 70)
        self.set_position(1)
        self.box = self.get_content_area()

        self.grid = Gtk.Grid()
        self.box.add(self.grid)

        self.label = Gtk.Label(label=f"{LABEL}:\t")
        self.grid.add(self.label)

        self.entry = Gtk.Entry()
        self.entry.set_visibility(False)
        self.entry.connect("activate", self.ok)
        self.grid.add(self.entry)

        self.button = Gtk.Button(label="OK")
        self.button.connect("clicked", self.ok)
        self.grid.attach_next_to(self.button, self.entry, Gtk.PositionType.BOTTOM, 1, 2)

        self.show_all()

    def ok(self, button):
        password = self.entry.get_text()
        if not password:
            exit(1)
        self.destroy()
        print(password)

# program
if __name__ == "__main__":
        with open(os.devnull, "w") as file:
            stdout, sys.stdout = sys.stdout, file
            stderr, sys.stderr = sys.stderr, file
            try:
                LABEL = sys.argv[1]
            except IndexError:
                LABEL = "password"
            try:
                    dialog = AskPassDialog()
            except RuntimeError:
                sys.stdout = stdout
                sys.stderr = stderr
                print(getpass(prompt=LABEL+": "))
                exit()
            sys.stdout = stdout
            sys.stderr = stderr
            dialog.run()

