name: base
channels:
  - conda-forge
dependencies:
  - python=3.10
  - mamba==0.22.1
  - conda==4.12.0
  - altair
  - black
  - bokeh
  - ca-certificates
  - certifi
  - h5py
  - ipympl
  - ipywidgets
  - isort
  - jupyter_bokeh
  - jupyterhub
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab_vim
  - matplotlib
  - numpy
  - openssl
  - orjson
  - pandas
  - pip
  - plotly
  - pyright
  - scipy
  - pip:
    - h5grove
    - jupyterlab-code-formatter
    - jupyterlab-hdf
    - tifffile
    - jupyter-server-proxy
