name: base
channels:
  - conda-forge
dependencies:
  - python=3.10
  - altair
  - black
  - bokeh
  - ca-certificates
  - certifi
  - h5py
  - ipympl
  - ipywidgets
  - isort
  - jupyter_bokeh
  - jupyterhub
  - jupyterlab
  - jupyterlab-git
  - jupyterlab-lsp
  - jupyterlab_vim
  - matplotlib
  - numpy
  - openssl
  - orjson
  - pandas
  - pip
  - plotly
  - pyright
  - scipy
  - h5grove
  - jupyterlab_code_formatter
  - tifffile
  - jupyter-server-proxy
  - pip:
    - jupyterlab-hdf
