#!/usr/bin/python
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

from datetime import datetime, timedelta

def is_leapyear(year: int):
    feb29 = datetime(year, 2, 28) + timedelta(days=1)
    return int(feb29.strftime("%d")) == 29

today = datetime.today()
day = int(today.strftime("%d"))
month = int(today.strftime("%m"))
last_month = int((month-2)%12+1)
year = int(today.strftime("%Y"))
months = {
    1: range(1, 32),
    2: range(1, 30) if is_leapyear(year) else range(1, 29),
    3: range(1, 32),
    4: range(1, 31),
    5: range(1, 32),
    6: range(1, 31),
    7: range(1, 32),
    8: range(1, 32),
    9: range(1, 31),
    10: range(1, 32),
    11: range(1, 31),
    12: range(1, 32),
}

days = list(months[month])
last_days = list(months[last_month])

first_day = (today - timedelta(days=day - 1)).weekday()
last_day = datetime(year, month, days[-1]).weekday()
days = ([] if first_day == 0 else last_days[-first_day:]) + days + [i+1 for i in range(6-last_day)]

calendar = "  | MO | TU | WE | TH | FR | SA | SU |  \n"
calendar += "  " + ("--|--"*8)[2:-2] + "  \n"
for i in range(0, len(days), 7):
    calendar += "  | " + " | ".join([f"{i:02d}" for i in days[i:i+7]]) + " | \n"
    calendar += "  " + ("--|--"*8)[2:-2] + "  \n"

if day < 15:
    calendar = calendar.replace(f" {day:02d} ", f"[{day:02d}]", 1)
else:
    l = len(calendar) // 3
    calendar1, calendar2 = calendar[:l], calendar[l:]
    calendar2 = calendar2.replace(f" {day:02d} ", f"[{day:02d}]")
    calendar = calendar1+calendar2

print(calendar)
