#!/usr/bin/env bash
convert -quality 0.5 -resize 1920x1080 -negate ~/.config/wallpaper.png /tmp/lockscreen.png;
i3lock --image ~/.cache/lockscreen.png --tiling --ignore-empty-password --show-failed-attempts

