#!/usr/bin/env bash
# change matplotlib style globally
# NOTE: for this to work, you need to have matplotlib
# stylesheets in ~/.config/matplotlib/stylelib/
if [[ "$1" =~ "list" ]]; then
    CWD=$PWD;
    cd $HOME/.config/matplotlib/stylelib ;
    ls *.mplstyle | sed -e 's/\..*$//';
    cd $CWD;
else
    cp $HOME/.config/matplotlib/stylelib/"$1".mplstyle $HOME/.config/matplotlib/matplotlibrc ;
fi
