#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____ 
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \  
#   | |   | |_/\| |-|||  __/| \_/||    /  | |  
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/  
#

DEFAULT="#f8df9c"
# DEFAULT="http://getwallpapers.com/wallpaper/full/f/8/1/74346.jpg"
# DEFAULT="https://www.pixelstalk.net/wp-content/uploads/2016/06/HD-Minimal-Wallpapers.png"

if [ $1 ]; then
    WALL=$1
else
    WALL=$DEFAULT
fi

# set current background file as background
if [ $WALL = $HOME/.config/wallpaper.png ] && [ ! $2 ]; then
    feh --bg-scale --no-fehbg ~/.config/wallpaper.png
    exit 0
fi

# set a color as background
if [[ $WALL == "#"* && ${#WALL} == 7 ]]; then
    if [ $2 ]; then
        >&2 echo "cannot use extra arguments when specifying a color as background"
        exit 1
    fi
    convert -size 1x1 xc:"$WALL" ~/.config/wallpaper.png
    set_wallpaper ~/.config/wallpaper.png
    exit 0
fi

# try to copy file
cp "$WALL" /tmp/wall

# if copying fails, it's probably a URL, download it with curl.
if [ $? -ne 0 ]; then
    curl "$WALL" -o /tmp/wall
fi

# convert downloaded file to ~/.config/wallpaper.png
convert -quality 100 -resize 1920x1080 $2 /tmp/wall ~/.config/wallpaper.png

# and convert the inverse of the file to ~/.config/lockscreen.png
convert -quality 100  -negate ~/.config/wallpaper.png ~/.config/lockscreen.png

# give some time to finish conversions
sleep 2

# update the background
set_wallpaper ~/.config/wallpaper.png
