#!/usr/bin/env bash

# This script behaves differently according to the currently active window.
# option 1: nemo is selected: close nemo and open currently open folder in st with --classname nemo
# option 2: st with --classname nemo is selected: close st and open currently open folder in nemo
# option 3: any other case: open nemo.

# this script is supposed to be mapped to super+n in sxhkdrc:
keymap="super+Control_L+n"

# get window information
window=$(xdotool getactivewindow)
windowtitle=$(xdotool getwindowname $window)
windowclass=$(xprop -id $window | grep WM_CLASS | sed 's/^.*\"\(.*\)\".*/\1/g')

if [[ $windowclass == "Nemo" ]]; then
    xdotool keyup $keymap && xdotool key alt+t && xdotool windowclose $window
elif [[ $windowtitle == "st-nemo" ]]; then
    xdotool keyup $keymap && xdotool key --window $window --delay 10 n e m o space period space ampersand exclam Return
    xdotool windowclose $window
else
    nemo $@
fi
