#!/bin/sh
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

# improved joplin sync script that syncs both TUI and GUI (not only TUI)

if ps -Af | grep -v grep | grep -v joplin-sync | grep joplin; then
    echo "Running joplin instance found. Syncing joplin skipped."
    exit 1
fi

ln -f "$HOME/.config/joplin/database.sqlite" "$HOME/.config/joplin/database.tui.sqlite"
ln -f "$HOME/.config/joplin-desktop/database.sqlite" "$HOME/.config/joplin/database.sqlite"

echo "syncing joplin GUI..."
joplin sync

ln -f "$HOME/.config/joplin/database.tui.sqlite" "$HOME/.config/joplin/database.sqlite"
echo "syncing joplin TUI..."
joplin sync
