#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

prompt="[sudo] password for $USER          "
if [ $1 ]; then
    prompt=$1;
fi

if [ -x /usr/local/bin/dmenu ]; then # custom dmenu build
    echo -n | /usr/local/bin/dmenu -P -p "$prompt" -fn monospace-18
else # standard pacman dmenu build
    echo -n "" | /usr/bin/dmenu -p "$prompt" -nb "#fdf6e3" -nf "#fdf6e3" -sb "#2aa198" -sf "#fdf6e3" -fn monospace-18
fi

