#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

# imports
import os
import sys
import time
from subprocess import Popen, call, check_output, PIPE, CalledProcessError
try:
    import pyautogui
except:
    pyautogui = None
with open(os.devnull, "w") as out:
    has_xdotool = not call(["which", "xdotool"], stdout=out, stderr=out)

# functions
def dmenu(list_in, prompt=""):
    time.sleep(0.1)
    prompt = [] if not prompt else ["-p", prompt.replace(" ", "-")]
    try:
        dmenu_in = Popen(["echo", "\n".join(list_in)], stdout=PIPE).stdout
        choice = check_output(
            ["dmenu"] + prompt + sys.argv[2:], stdin=dmenu_in
        ).decode().strip()
        return choice
    except CalledProcessError:
        return ""

def notify(title, message=""):
    if message:
        check_output(["notify-send", title, message])
    else:
        check_output(["notify-send", title])

def copy_to_clipboard(content):
    xclip_in = Popen(["echo", "-n", content], stdout=PIPE).stdout
    status = call(["xclip", "-selection", "primary"], stdin=xclip_in)
    xclip_in = Popen(["echo", "-n", content], stdout=PIPE).stdout
    status = call(["xclip", "-selection", "clipboard"], stdin=xclip_in)
    return status

def get_emails(filename="~/.local/share/contacts/contacts.vcf"):
    filename = os.path.abspath(os.path.expanduser(filename))
    emails = {}
    with open(filename, "r") as file:
        content = file.read()
    cards = content.split("BEGIN:VCARD")
    for card in cards:
        if "EMAIL" in card:
            name, email = "", ""
            for line in card.split("\n"):
                if line.startswith("N:"):
                    name = line.split(":")[1].split(";")[:2]
                    name = f"{name[1].strip()} {name[0].strip()}"
                if line.startswith("EMAIL"):
                    email = line.split(":")[-1].strip()
            if name and email:
                key = f"{name} ({email})"
                emails[key] = email
    return emails

def get_current_window_name_and_position():
    if not has_xdotool:
        return "", 0, 0
    window_id = check_output(["xdotool", "getactivewindow"]).strip().decode()
    name = check_output(["xdotool", "getwindowname", window_id]).strip().decode()
    geometry = check_output(["xdotool", "getwindowgeometry", window_id]).strip().decode()
    x, y = geometry.split("Position: ")[1].split(" ")[0].split(",")
    return name, x, y

def move_mouse(x, y):
    if not has_xdotool:
        return 1
    return call(["xdotool", "mousemove", x, y])

def middle_click():
    if not has_xdotool:
        return 1
    return call(["xdotool", "click", "2"])

def paste_email(email):
    if windowname in {"st", "xterm", "urxvt"}:
        if not has_xdotool:
            notify(f"'{email}' copied to clipboard.")
            exit(0)
        middle_click()
    elif pyautogui is not None:
        middle_click()
        pyautogui.press("apps")
        pyautogui.hotkey("ctrl", "v")
    elif has_xdotool:
        middle_click()
    else:
        notify(f"'{email}' copied to clipboard.")

# program
if __name__ == "__main__":
    emails = get_emails()
    windowname, x, y = get_current_window_name_and_position()
    name = dmenu(emails.keys())
    email = emails.get(name, "")
    if email:
        status = copy_to_clipboard(email)
        move_mouse(x, y)
        paste_email(email)

