#!/usr/bin/env bash

message() {
    if [ $1 ]; then
        notify-send "$3 $2" "success!"
    else
        notify-send "$3 $2" "failed."
    fi
}

service=$( ls /etc/systemd/system/ /usr/lib/systemd/system/ | dmenu -l 20 -p "select service" $@)

if [ ! $service ]; then
    notify-send "no service selected"
    exit 1
fi

if [[ $service == *:* ]]; then
    notify-send "no valid service selected"
    exit 1
fi


if [[ $(systemctl is-active $service) == "active" ]]; then
    sudo -A systemctl stop $service
    message $? $service "stop"
    dwm_status
else
    sudo -A systemctl restart $service;
    message $? $service "start"
    dwm_status
fi
