#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

import os
import sys
from time import sleep
from subprocess import call, check_output, CalledProcessError, Popen, PIPE

# check if picom is running
with open(os.devnull, "w") as file:
    picom = not call(["pidof", "picom"], stdout=file, stderr=file)

# get possible layouts
layouts = os.listdir(os.path.expanduser("~/.scripts/screenlayout"))
layouts = ["default_screenlayout", "same", "last"] + sorted(
    [layout for layout in layouts if layout[0] == "["]
)

# pipe the layouts as input commands [to dmenu]
commands = Popen(["printf", "\n".join(layouts)], stdout=PIPE).stdout

# take the input commands and select one with dmenu
try:
    command = check_output(["dmenu", "-p", " "] + sys.argv[1:], stdin=commands).decode().strip()
    if command == "default_screenlayout":
        os.remove(os.path.expanduser("~/.scripts/screenlayout/last")) # otherwise default_screenlayout will default to last
    # call the final layout command
    call([os.path.join(os.path.expanduser("~/.scripts/screenlayout"), command)])
except CalledProcessError:
    pass

sleep(1)

# reset keystroke repeat rate
Popen(["xset", "r", "rate", "200", "45"])

# restart picom if it was running
with open(os.devnull, "w") as file:
    if picom and call(["pidof", "picom"], stdout=file, stderr=file):
        Popen(["picom", "--experimental-backends"], stdout=file, stderr=file)

