#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

from python_dmenu_lib import *

def get_codepoints():
    codepoints = {}
    with open("/usr/share/fonts/awesome-terminal-fonts/pomicons-regular.sh", "rb") as file:
        for line in file:
            if line.startswith(b"CODEPOINT_OF_POMICONS_"):
                name, codepoint = line.split(b"=")
                name = name.replace(b"CODEPOINT_OF_POMICONS_", b"").decode().lower().strip().replace("_", " ")
                codepoint = codepoint.replace(b"'",b"").replace(b'"', b"").lower().strip()
                codepoints[name] = (b"\u" + codepoint).decode("unicode-escape")
    with open("/usr/share/fonts/awesome-terminal-fonts/fontawesome-regular.sh", "rb") as file:
        for line in file:
            if line.startswith(b"CODEPOINT_OF_AWESOME_"):
                name, codepoint = line.split(b"=")
                name = name.replace(b"CODEPOINT_OF_AWESOME_", b"").decode().lower().strip().replace("_", " ")
                codepoint = codepoint.replace(b"'",b"").replace(b'"', b"").lower().strip()
                codepoints[name] = (b"\u" + codepoint).decode("unicode-escape")
    with open("/usr/share/fonts/awesome-terminal-fonts/octicons-regular.sh", "rb") as file:
        for line in file:
            if line.startswith(b"CODEPOINT_OF_OCTICONS_"):
                name, codepoint = line.split(b"=")
                name = name.replace(b"CODEPOINT_OF_OCTICONS_", b"").decode().lower().strip().replace("_", " ")
                codepoint = codepoint.replace(b"'",b"").replace(b'"', b"").lower().strip()
                codepoints[name] = (b"\u" + codepoint).decode("unicode-escape")
    with open("/usr/share/fonts/awesome-terminal-fonts/devicons-regular.sh", "rb") as file:
        for line in file:
            if line.startswith(b"CODEPOINT_OF_DEVICONS_"):
                name, codepoint = line.split(b"=")
                name = name.replace(b"CODEPOINT_OF_DEVICONS_", b"").decode().lower().strip().replace("_", " ")
                codepoint = codepoint.replace(b"'",b"").replace(b'"', b"").lower().strip()
                codepoints[name] = (b"\u" + codepoint).decode("unicode-escape")
    codepoints = {f"{k} {codepoints[k]}": codepoints[k] for k in sorted(codepoints.keys())}
    return codepoints

if __name__ == "__main__":
    exit(main(get_codepoints, " "))

