#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/

import os
import sys
from subprocess import call, check_output, CalledProcessError, Popen, PIPE

# get possible layouts
layouts = os.listdir(os.path.expanduser("~/.scripts/screenlayout"))
layouts = ["default_screenlayout", "same", "last"] + sorted(
    [layout for layout in layouts if layout[0] == "["]
)

# pipe the layouts as input commands [to dmenu]
commands = Popen(["printf", "\n".join(layouts)], stdout=PIPE).stdout

# take the input commands and select one with dmenu
try:
    command = check_output(["dmenu"] + sys.argv[1:], stdin=commands).decode().strip()
    if command == "default_screenlayout":
        os.remove(os.path.expanduser("~/.scripts/screenlayout/last")) # otherwise default_screenlayout will default to last
    # call the final layout command
    call([os.path.join(os.path.expanduser("~/.scripts/screenlayout"), command)])
except CalledProcessError:
    pass
