#!/usr/bin/python3
#    _____ _     ____  ____  ____  ____  _____
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \
#   | |   | |_/\| |-|||  __/| \_/||    /  | |
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/
#

from python_dmenu_lib import *

def get_emojis(filename="~/.scripts/dmenu/emoji.txt"):
    filename = os.path.abspath(os.path.expanduser(filename))
    emojis = {}
    with open(filename, "r") as file:
        for line in file:
            line = line.split(";")[0].split(" ")
            emoji = line[0].strip()
            name = " ".join(line[1:]).strip()
            name = f"{name} {emoji}"
            emojis[name] = emoji
    return emojis

if __name__ == "__main__":
    exit(main(get_emojis, "😀"))

