require("pluginmanager")
require("telescope.builtin")
require("fixed")
require("commands")
require("keybindings")
require("colors")
require("variables")
require("filetypes")

vim.cmd([[source ~/.config/nvim/vim/other_settings.vim ]])
vim.cmd([[source ~/.config/nvim/vim/latex.vim ]])
vim.cmd([[source ~/.config/nvim/vim/neovim.vim ]])
vim.cmd([[source ~/.config/nvim/vim/python.vim ]])
vim.cmd([[source ~/.config/nvim/vim/rust.vim ]])
vim.cmd([[source ~/.config/nvim/vim/yaml.vim ]])
