require("pluginmanager")
require("telescope.builtin")
require("fixed")
require("commands")
require("colors")
require("variables")
require("filetypes")

vim.cmd([[source ~/.config/nvim/vim/commands.vim ]])
vim.cmd([[source ~/.config/nvim/vim/keybindings.vim ]])
vim.cmd([[source ~/.config/nvim/vim/latex.vim ]])
vim.cmd([[source ~/.config/nvim/vim/neovim.vim ]])
vim.cmd([[source ~/.config/nvim/vim/python.vim ]])
vim.cmd([[source ~/.config/nvim/vim/rust.vim ]])
vim.cmd([[source ~/.config/nvim/vim/yaml.vim ]])
