#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____ 
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \  
#   | |   | |_/\| |-|||  __/| \_/||    /  | |  
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/  
#

SESSIONNAME=$1

if tmux ls | grep $SESSIONNAME; then
    echo "tmux already running.";
else
    echo "starting tmux...";
    tmux new-session -s $SESSIONNAME -d;
    tmux send-keys -t $SESSIONNAME bash Enter
fi

sleep 0.05;

