#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____ 
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \  
#   | |   | |_/\| |-|||  __/| \_/||    /  | |  
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/  
#

WINDOWNAME=$1

if xwininfo -tree -root | grep $WINDOWNAME;
then
    echo "Window detected."
    i3 [instance="$WINDOWNAME"] scratchpad show;
else
    echo "Window not detected... spawning."
    ($TERMINAL -n $WINDOWNAME -e tmux attach-session -t $WINDOWNAME) & disown;
    sleep 0.15;
    i3 [instance="$WINDOWNAME"] scratchpad show;
fi
