#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____ 
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \  
#   | |   | |_/\| |-|||  __/| \_/||    /  | |  
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/  
#

if [[ "$1" == *.py ]]; then
    ~/.config/nvim/run_python $1
elif [[ "$1" == *.md ]]; then
    ~/.config/nvim/run_markdown $1
elif [[ "$1" == *.tex ]]; then
    ~/.config/nvim/run_latex $1
else
    echo "not able to run $1"
fi
