#!/usr/bin/env bash

if [[ "$1" == *.py ]]; then
    ~/.config/nvim/run_python $1
elif [[ "$1" == *.md ]]; then
    ~/.config/nvim/run_markdown $1
elif [[ "$1" == *.tex ]]; then
    ~/.config/nvim/run_latex $1
else
    echo "not able to run $1"
fi
