#!/usr/bin/env bash

# run a file in a tmux session named after the command to run it

COMMAND="grip"
FILENAME=$1


~/.config/nvim/make_tmux_session $COMMAND

tmux send-keys -t $COMMAND C-c Enter
echo "previewing markdown... "
tmux send-keys -t $COMMAND cd Space $PWD Enter $COMMAND Space -b Space $FILENAME Enter;

#~/.config/nvim/open_i3_window $COMMAND

