#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____ 
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \  
#   | |   | |_/\| |-|||  __/| \_/||    /  | |  
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/  
#

# run a file in a tmux session named after the command to run it

COMMAND="grip"
FILENAME=$1
PORT=7777

if type surf &> /dev/null; then
    BROWSER="surf "
else
    BROWSER="chromium --app="
fi

~/.config/nvim/make_tmux_session $COMMAND

tmux send-keys -t $COMMAND C-c Enter
echo "previewing markdown... "
tmux send-keys -t $COMMAND cd Space $PWD Enter $COMMAND Space $FILENAME Space $PORT Enter;


sleep 0.5

$BROWSER"http://localhost:$PORT"

