#!/usr/bin/env bash
#    _____ _     ____  ____  ____  ____  _____ 
#   /    // \   /  _ \/  __\/  _ \/  __\/__ __\
#   |  __\| |   | / \||  \/|| / \||  \/|  / \  
#   | |   | |_/\| |-|||  __/| \_/||    /  | |  
#   \_/   \____/\_/ \|\_/   \____/\_/\_\  \_/  
#

if [[ "$1" == *.py ]]; then
    ~/.config/nvim/run_python_selection $1;
else
    echo "not able to run selection for $1";
fi
