#!/usr/bin/env python3

## standard library imports
import os
import sys
from subprocess import check_output, call, Popen, PIPE, CalledProcessError

##  custom functions
def ext(s):
    """ get extension from path """
    return os.path.splitext(s)[-1]

def port(args):
    """ get port string from arguments """
    try:
        port = int(args[0])
        del args[0]
    except (IndexError, ValueError):
        # special exception for tex files, which always should be opened
        # inside nvr for synctex to work (see zathura configuration)
        if any(ext(filename) == ".tex" for filename in args):
            port = 9999
        else:
            return None
    if port < 1000:
        port += 10000
    return [f"127.0.0.1:{port}"]

## constants
NUM_ARGS = len(sys.argv) - 1
ARGS = sys.argv[1:]
PORT = port(ARGS)
FIND = ["find", ".", "-type", "f"]
FZF = ["fzf"]
NVIM = ["/usr/bin/nvim"]
NVR  = ["/usr/bin/nvr", "--servername"]

## actual script
if NUM_ARGS > 0:
    if PORT:
        command = NVR + PORT + ARGS
    else:
        command = NVIM + ARGS
    call(command)
else: # find filename with fzf
    find_out = Popen(FIND, stdout=PIPE).stdout
    try:
        filename = check_output(FZF, stdin=find_out)[:-1].decode()
        if ext(filename) == ".tex":
            call(NVR + ["127.0.0.1:9999", filename])
        else:
            call(NVIM + [filename])
    except CalledProcessError:
        call(NVIM)
