#!/bin/bash

sc=$(cat ~/.soundcard)
string=$(amixer -c $sc get Master)
if [[ $string == *"[on]"* ]]; then
    percentage=$(echo $(amixer -c $sc get Master) | cut -d "[" -f2 | cut -d "]" -f1)
    echo 🔊" "$percentage
else
  echo 🔇
fi
