#!/bin/bash

sc=$($HOME/.scripts/soundcard)
string=$(amixer -c $sc get Master)
if [[ $string == *"[on]"* ]]; then
    percentage=$(echo $(amixer -c $sc get Master) | cut -d "[" -f2 | cut -d "]" -f1)
    echo 🔊" "$percentage
else
  echo 🔇
fi

show() {
    $HOME/.scripts/non-transparent-terminal -n volume -f mono:pixelsize=12 -e alsamixer;
}

case $BLOCK_BUTTON in
    1) show ;;
esac
